// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ArchiveMember {
    /**
     * Creates a new ArchiveMember instance.
     * @param {Partial<ArchiveMember>} [$$source = {}] - The source object to create the ArchiveMember.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("compressedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["compressedBytes"] = 0;
        }
        if (!("uncompressedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uncompressedBytes"] = 0;
        }
        if (!("crc32" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["crc32"] = 0;
        }
        if (!("method" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["method"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["modifiedAt"] = undefined;
        }
        if (!("directory" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["directory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchiveMember instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArchiveMember}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchiveMember(/** @type {Partial<ArchiveMember>} */($$parsedSource));
    }
}

export class ExportResult {
    /**
     * Creates a new ExportResult instance.
     * @param {Partial<ExportResult>} [$$source = {}] - The source object to create the ExportResult.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("entryCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entryCount"] = 0;
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResult(/** @type {Partial<ExportResult>} */($$parsedSource));
    }
}

export class FileSnapshot {
    /**
     * Creates a new FileSnapshot instance.
     * @param {Partial<FileSnapshot>} [$$source = {}] - The source object to create the FileSnapshot.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("modifiedNs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modifiedNs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileSnapshot instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FileSnapshot}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileSnapshot(/** @type {Partial<FileSnapshot>} */($$parsedSource));
    }
}

export class ImageCandidate {
    /**
     * Creates a new ImageCandidate instance.
     * @param {Partial<ImageCandidate>} [$$source = {}] - The source object to create the ImageCandidate.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("role" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["role"] = "";
        }
        if (!("uncompressedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uncompressedBytes"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["width"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["height"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["mime"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["assetId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageCandidate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImageCandidate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageCandidate(/** @type {Partial<ImageCandidate>} */($$parsedSource));
    }
}

export class Issue {
    /**
     * Creates a new Issue instance.
     * @param {Partial<Issue>} [$$source = {}] - The source object to create the Issue.
     */
    constructor($$source = {}) {
        if (!("code" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["code"] = "";
        }
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {Severity}
             */
            this["severity"] = Severity.$zero;
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["path"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Issue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Issue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Issue(/** @type {Partial<Issue>} */($$parsedSource));
    }
}

export class JBeamStats {
    /**
     * Creates a new JBeamStats instance.
     * @param {Partial<JBeamStats>} [$$source = {}] - The source object to create the JBeamStats.
     */
    constructor($$source = {}) {
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["files"] = 0;
        }
        if (!("parsedFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["parsedFiles"] = 0;
        }
        if (!("declaredNodes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["declaredNodes"] = 0;
        }
        if (!("declaredBeams" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["declaredBeams"] = 0;
        }
        if (!("declaredTriangles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["declaredTriangles"] = 0;
        }
        if (!("declaredSlots" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["declaredSlots"] = 0;
        }
        if (!("declaredHydros" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["declaredHydros"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["controllers"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JBeamStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JBeamStats}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("controllers" in $$parsedSource) {
            $$parsedSource["controllers"] = $$createField7_0($$parsedSource["controllers"]);
        }
        return new JBeamStats(/** @type {Partial<JBeamStats>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Kind = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    KindVehicle: "vehicle",
    KindMap: "map",
    KindUI: "ui",
    KindScript: "script",
    KindMixed: "mixed",
    KindUnknown: "unknown",
};

export class Manifest {
    /**
     * Creates a new Manifest instance.
     * @param {Partial<Manifest>} [$$source = {}] - The source object to create the Manifest.
     */
    constructor($$source = {}) {
        if (!("schemaVersion" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["schemaVersion"] = 0;
        }
        if (!("analyzerVersion" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["analyzerVersion"] = "";
        }
        if (!("analyzedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["analyzedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("archivePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivePath"] = "";
        }
        if (!("filename" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filename"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("modifiedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modifiedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("centralFingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["centralFingerprint"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fullSha256"] = undefined;
        }
        if (!("validArchive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["validArchive"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["wrapper"] = undefined;
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {Kind}
             */
            this["kind"] = Kind.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["contentTags"] = undefined;
        }
        if (!("namespaces" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: string[] }}
             */
            this["namespaces"] = {};
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["author"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["version"] = undefined;
        }
        if (!("entryCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entryCount"] = 0;
        }
        if (!("compressedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["compressedBytes"] = 0;
        }
        if (!("uncompressedBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uncompressedBytes"] = 0;
        }
        if (!("members" in $$source)) {
            /**
             * @member
             * @type {ArchiveMember[]}
             */
            this["members"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {MetadataDocument[] | undefined}
             */
            this["metadataDocuments"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {ImageCandidate[] | undefined}
             */
            this["images"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["selectedImagePath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Variant[] | undefined}
             */
            this["variants"] = undefined;
        }
        if (!("jbeam" in $$source)) {
            /**
             * @member
             * @type {JBeamStats}
             */
            this["jbeam"] = (new JBeamStats());
        }
        if (!("map" in $$source)) {
            /**
             * @member
             * @type {MapStats}
             */
            this["map"] = (new MapStats());
        }
        if (!("ui" in $$source)) {
            /**
             * @member
             * @type {UIStats}
             */
            this["ui"] = (new UIStats());
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {Issue[] | undefined}
             */
            this["issues"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Manifest}
     */
    static createFrom($$source = {}) {
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType1;
        const $$createField21_0 = $$createType3;
        const $$createField22_0 = $$createType5;
        const $$createField23_0 = $$createType7;
        const $$createField25_0 = $$createType9;
        const $$createField26_0 = $$createType10;
        const $$createField27_0 = $$createType11;
        const $$createField28_0 = $$createType12;
        const $$createField29_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contentTags" in $$parsedSource) {
            $$parsedSource["contentTags"] = $$createField12_0($$parsedSource["contentTags"]);
        }
        if ("namespaces" in $$parsedSource) {
            $$parsedSource["namespaces"] = $$createField13_0($$parsedSource["namespaces"]);
        }
        if ("members" in $$parsedSource) {
            $$parsedSource["members"] = $$createField21_0($$parsedSource["members"]);
        }
        if ("metadataDocuments" in $$parsedSource) {
            $$parsedSource["metadataDocuments"] = $$createField22_0($$parsedSource["metadataDocuments"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField23_0($$parsedSource["images"]);
        }
        if ("variants" in $$parsedSource) {
            $$parsedSource["variants"] = $$createField25_0($$parsedSource["variants"]);
        }
        if ("jbeam" in $$parsedSource) {
            $$parsedSource["jbeam"] = $$createField26_0($$parsedSource["jbeam"]);
        }
        if ("map" in $$parsedSource) {
            $$parsedSource["map"] = $$createField27_0($$parsedSource["map"]);
        }
        if ("ui" in $$parsedSource) {
            $$parsedSource["ui"] = $$createField28_0($$parsedSource["ui"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField29_0($$parsedSource["issues"]);
        }
        return new Manifest(/** @type {Partial<Manifest>} */($$parsedSource));
    }
}

export class MapStats {
    /**
     * Creates a new MapStats instance.
     * @param {Partial<MapStats>} [$$source = {}] - The source object to create the MapStats.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["levelIds"] = undefined;
        }
        if (!("terrainFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["terrainFiles"] = 0;
        }
        if (!("levelObjectFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["levelObjectFiles"] = 0;
        }
        if (!("forestFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["forestFiles"] = 0;
        }
        if (!("facilityFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["facilityFiles"] = 0;
        }
        if (!("materialFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["materialFiles"] = 0;
        }
        if (!("modelFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modelFiles"] = 0;
        }
        if (!("textureFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["textureFiles"] = 0;
        }
        if (!("spawnPoints" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["spawnPoints"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MapStats}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("levelIds" in $$parsedSource) {
            $$parsedSource["levelIds"] = $$createField0_0($$parsedSource["levelIds"]);
        }
        return new MapStats(/** @type {Partial<MapStats>} */($$parsedSource));
    }
}

export class MetadataDocument {
    /**
     * Creates a new MetadataDocument instance.
     * @param {Partial<MetadataDocument>} [$$source = {}] - The source object to create the MetadataDocument.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["data"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataDocument instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MetadataDocument}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new MetadataDocument(/** @type {Partial<MetadataDocument>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const Severity = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    SeverityInfo: "info",
    SeverityWarning: "warning",
    SeverityError: "error",
};

export class UIStats {
    /**
     * Creates a new UIStats instance.
     * @param {Partial<UIStats>} [$$source = {}] - The source object to create the UIStats.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string[] | undefined}
             */
            this["appRoots"] = undefined;
        }
        if (!("htmlFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["htmlFiles"] = 0;
        }
        if (!("cssFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cssFiles"] = 0;
        }
        if (!("javaScriptFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["javaScriptFiles"] = 0;
        }
        if (!("luaFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["luaFiles"] = 0;
        }
        if (!("settingsFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["settingsFiles"] = 0;
        }
        if (!("scriptFiles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scriptFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UIStats}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appRoots" in $$parsedSource) {
            $$parsedSource["appRoots"] = $$createField0_0($$parsedSource["appRoots"]);
        }
        return new UIStats(/** @type {Partial<UIStats>} */($$parsedSource));
    }
}

export class ValidationResult {
    /**
     * Creates a new ValidationResult instance.
     * @param {Partial<ValidationResult>} [$$source = {}] - The source object to create the ValidationResult.
     */
    constructor($$source = {}) {
        if (!("valid" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["valid"] = false;
        }
        if (!("issues" in $$source)) {
            /**
             * @member
             * @type {Issue[]}
             */
            this["issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ValidationResult}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField1_0($$parsedSource["issues"]);
        }
        return new ValidationResult(/** @type {Partial<ValidationResult>} */($$parsedSource));
    }
}

export class Variant {
    /**
     * Creates a new Variant instance.
     * @param {Partial<Variant>} [$$source = {}] - The source object to create the Variant.
     */
    constructor($$source = {}) {
        if (!("namespace" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["namespace"] = "";
        }
        if (!("baseName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["baseName"] = "";
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["metadataPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["thumbnailPath"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["configuration"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["description"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["configType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["bodyStyle"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["drivetrain"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["transmission"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["fuelType"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["propulsion"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["power"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["torque"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["weight"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["topSpeed"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["fields"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Variant instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Variant}
     */
    static createFrom($$source = {}) {
        const $$createField18_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField18_0($$parsedSource["fields"]);
        }
        return new Variant(/** @type {Partial<Variant>} */($$parsedSource));
    }
}

export class WorkspaceChange {
    /**
     * Creates a new WorkspaceChange instance.
     * @param {Partial<WorkspaceChange>} [$$source = {}] - The source object to create the WorkspaceChange.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["beforeSha"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["afterSha"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {number | undefined}
             */
            this["sizeBytes"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["textDiff"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceChange instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceChange}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceChange(/** @type {Partial<WorkspaceChange>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = ArchiveMember.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = MetadataDocument.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ImageCandidate.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Variant.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = JBeamStats.createFrom;
const $$createType11 = MapStats.createFrom;
const $$createType12 = UIStats.createFrom;
const $$createType13 = Issue.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Map($Create.Any, $Create.Any);
