// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class ArchiveMember {
    "path": string;
    "compressedBytes": number;
    "uncompressedBytes": number;
    "crc32": number;
    "method": number;
    "modifiedAt"?: string;
    "directory": boolean;

    /** Creates a new ArchiveMember instance. */
    constructor($$source: Partial<ArchiveMember> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("compressedBytes" in $$source)) {
            this["compressedBytes"] = 0;
        }
        if (!("uncompressedBytes" in $$source)) {
            this["uncompressedBytes"] = 0;
        }
        if (!("crc32" in $$source)) {
            this["crc32"] = 0;
        }
        if (!("method" in $$source)) {
            this["method"] = 0;
        }
        if (!("directory" in $$source)) {
            this["directory"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchiveMember instance from a string or object.
     */
    static createFrom($$source: any = {}): ArchiveMember {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchiveMember($$parsedSource as Partial<ArchiveMember>);
    }
}

export class ExportResult {
    "path": string;
    "sha256": string;
    "sizeBytes": number;
    "createdAt": string;
    "entryCount": number;
    "fingerprint": string;

    /** Creates a new ExportResult instance. */
    constructor($$source: Partial<ExportResult> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("entryCount" in $$source)) {
            this["entryCount"] = 0;
        }
        if (!("fingerprint" in $$source)) {
            this["fingerprint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ExportResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportResult($$parsedSource as Partial<ExportResult>);
    }
}

export class FileSnapshot {
    "path": string;
    "sha256": string;
    "sizeBytes": number;
    "modifiedNs": number;

    /** Creates a new FileSnapshot instance. */
    constructor($$source: Partial<FileSnapshot> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("sha256" in $$source)) {
            this["sha256"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("modifiedNs" in $$source)) {
            this["modifiedNs"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FileSnapshot instance from a string or object.
     */
    static createFrom($$source: any = {}): FileSnapshot {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FileSnapshot($$parsedSource as Partial<FileSnapshot>);
    }
}

export class ImageCandidate {
    "path": string;
    "role": string;
    "uncompressedBytes": number;
    "width"?: number;
    "height"?: number;
    "mime"?: string;
    "assetId"?: string;

    /** Creates a new ImageCandidate instance. */
    constructor($$source: Partial<ImageCandidate> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("role" in $$source)) {
            this["role"] = "";
        }
        if (!("uncompressedBytes" in $$source)) {
            this["uncompressedBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImageCandidate instance from a string or object.
     */
    static createFrom($$source: any = {}): ImageCandidate {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImageCandidate($$parsedSource as Partial<ImageCandidate>);
    }
}

export class Issue {
    "code": string;
    "severity": Severity;
    "message": string;
    "path"?: string;

    /** Creates a new Issue instance. */
    constructor($$source: Partial<Issue> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }
        if (!("severity" in $$source)) {
            this["severity"] = Severity.$zero;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Issue instance from a string or object.
     */
    static createFrom($$source: any = {}): Issue {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Issue($$parsedSource as Partial<Issue>);
    }
}

export class JBeamStats {
    "files": number;
    "parsedFiles": number;
    "declaredNodes": number;
    "declaredBeams": number;
    "declaredTriangles": number;
    "declaredSlots": number;
    "declaredHydros": number;
    "controllers"?: string[];

    /** Creates a new JBeamStats instance. */
    constructor($$source: Partial<JBeamStats> = {}) {
        if (!("files" in $$source)) {
            this["files"] = 0;
        }
        if (!("parsedFiles" in $$source)) {
            this["parsedFiles"] = 0;
        }
        if (!("declaredNodes" in $$source)) {
            this["declaredNodes"] = 0;
        }
        if (!("declaredBeams" in $$source)) {
            this["declaredBeams"] = 0;
        }
        if (!("declaredTriangles" in $$source)) {
            this["declaredTriangles"] = 0;
        }
        if (!("declaredSlots" in $$source)) {
            this["declaredSlots"] = 0;
        }
        if (!("declaredHydros" in $$source)) {
            this["declaredHydros"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JBeamStats instance from a string or object.
     */
    static createFrom($$source: any = {}): JBeamStats {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("controllers" in $$parsedSource) {
            $$parsedSource["controllers"] = $$createField7_0($$parsedSource["controllers"]);
        }
        return new JBeamStats($$parsedSource as Partial<JBeamStats>);
    }
}

export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindVehicle = "vehicle",
    KindMap = "map",
    KindUI = "ui",
    KindScript = "script",
    KindMixed = "mixed",
    KindUnknown = "unknown",
};

export class Manifest {
    "schemaVersion": number;
    "analyzerVersion": string;
    "analyzedAt": string;
    "archivePath": string;
    "filename": string;
    "sizeBytes": number;
    "modifiedAt": string;
    "centralFingerprint": string;
    "fullSha256"?: string;
    "validArchive": boolean;
    "wrapper"?: string;
    "kind": Kind;
    "contentTags"?: string[];
    "namespaces": { [_ in string]?: string[] };
    "title"?: string;
    "description"?: string;
    "author"?: string;
    "version"?: string;
    "entryCount": number;
    "compressedBytes": number;
    "uncompressedBytes": number;
    "members": ArchiveMember[];
    "metadataDocuments"?: MetadataDocument[];
    "images"?: ImageCandidate[];
    "selectedImagePath"?: string;
    "variants"?: Variant[];
    "jbeam": JBeamStats;
    "map": MapStats;
    "ui": UIStats;
    "issues"?: Issue[];

    /** Creates a new Manifest instance. */
    constructor($$source: Partial<Manifest> = {}) {
        if (!("schemaVersion" in $$source)) {
            this["schemaVersion"] = 0;
        }
        if (!("analyzerVersion" in $$source)) {
            this["analyzerVersion"] = "";
        }
        if (!("analyzedAt" in $$source)) {
            this["analyzedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("archivePath" in $$source)) {
            this["archivePath"] = "";
        }
        if (!("filename" in $$source)) {
            this["filename"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            this["sizeBytes"] = 0;
        }
        if (!("modifiedAt" in $$source)) {
            this["modifiedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("centralFingerprint" in $$source)) {
            this["centralFingerprint"] = "";
        }
        if (!("validArchive" in $$source)) {
            this["validArchive"] = false;
        }
        if (!("kind" in $$source)) {
            this["kind"] = Kind.$zero;
        }
        if (!("namespaces" in $$source)) {
            this["namespaces"] = {};
        }
        if (!("entryCount" in $$source)) {
            this["entryCount"] = 0;
        }
        if (!("compressedBytes" in $$source)) {
            this["compressedBytes"] = 0;
        }
        if (!("uncompressedBytes" in $$source)) {
            this["uncompressedBytes"] = 0;
        }
        if (!("members" in $$source)) {
            this["members"] = [];
        }
        if (!("jbeam" in $$source)) {
            this["jbeam"] = (new JBeamStats());
        }
        if (!("map" in $$source)) {
            this["map"] = (new MapStats());
        }
        if (!("ui" in $$source)) {
            this["ui"] = (new UIStats());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Manifest instance from a string or object.
     */
    static createFrom($$source: any = {}): Manifest {
        const $$createField12_0 = $$createType0;
        const $$createField13_0 = $$createType1;
        const $$createField21_0 = $$createType3;
        const $$createField22_0 = $$createType5;
        const $$createField23_0 = $$createType7;
        const $$createField25_0 = $$createType9;
        const $$createField26_0 = $$createType10;
        const $$createField27_0 = $$createType11;
        const $$createField28_0 = $$createType12;
        const $$createField29_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("contentTags" in $$parsedSource) {
            $$parsedSource["contentTags"] = $$createField12_0($$parsedSource["contentTags"]);
        }
        if ("namespaces" in $$parsedSource) {
            $$parsedSource["namespaces"] = $$createField13_0($$parsedSource["namespaces"]);
        }
        if ("members" in $$parsedSource) {
            $$parsedSource["members"] = $$createField21_0($$parsedSource["members"]);
        }
        if ("metadataDocuments" in $$parsedSource) {
            $$parsedSource["metadataDocuments"] = $$createField22_0($$parsedSource["metadataDocuments"]);
        }
        if ("images" in $$parsedSource) {
            $$parsedSource["images"] = $$createField23_0($$parsedSource["images"]);
        }
        if ("variants" in $$parsedSource) {
            $$parsedSource["variants"] = $$createField25_0($$parsedSource["variants"]);
        }
        if ("jbeam" in $$parsedSource) {
            $$parsedSource["jbeam"] = $$createField26_0($$parsedSource["jbeam"]);
        }
        if ("map" in $$parsedSource) {
            $$parsedSource["map"] = $$createField27_0($$parsedSource["map"]);
        }
        if ("ui" in $$parsedSource) {
            $$parsedSource["ui"] = $$createField28_0($$parsedSource["ui"]);
        }
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField29_0($$parsedSource["issues"]);
        }
        return new Manifest($$parsedSource as Partial<Manifest>);
    }
}

export class MapStats {
    "levelIds"?: string[];
    "terrainFiles": number;
    "levelObjectFiles": number;
    "forestFiles": number;
    "facilityFiles": number;
    "materialFiles": number;
    "modelFiles": number;
    "textureFiles": number;
    "spawnPoints": number;

    /** Creates a new MapStats instance. */
    constructor($$source: Partial<MapStats> = {}) {
        if (!("terrainFiles" in $$source)) {
            this["terrainFiles"] = 0;
        }
        if (!("levelObjectFiles" in $$source)) {
            this["levelObjectFiles"] = 0;
        }
        if (!("forestFiles" in $$source)) {
            this["forestFiles"] = 0;
        }
        if (!("facilityFiles" in $$source)) {
            this["facilityFiles"] = 0;
        }
        if (!("materialFiles" in $$source)) {
            this["materialFiles"] = 0;
        }
        if (!("modelFiles" in $$source)) {
            this["modelFiles"] = 0;
        }
        if (!("textureFiles" in $$source)) {
            this["textureFiles"] = 0;
        }
        if (!("spawnPoints" in $$source)) {
            this["spawnPoints"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MapStats instance from a string or object.
     */
    static createFrom($$source: any = {}): MapStats {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("levelIds" in $$parsedSource) {
            $$parsedSource["levelIds"] = $$createField0_0($$parsedSource["levelIds"]);
        }
        return new MapStats($$parsedSource as Partial<MapStats>);
    }
}

export class MetadataDocument {
    "path": string;
    "data": { [_ in string]?: any };

    /** Creates a new MetadataDocument instance. */
    constructor($$source: Partial<MetadataDocument> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("data" in $$source)) {
            this["data"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MetadataDocument instance from a string or object.
     */
    static createFrom($$source: any = {}): MetadataDocument {
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField1_0($$parsedSource["data"]);
        }
        return new MetadataDocument($$parsedSource as Partial<MetadataDocument>);
    }
}

export enum Severity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SeverityInfo = "info",
    SeverityWarning = "warning",
    SeverityError = "error",
};

export class UIStats {
    "appRoots"?: string[];
    "htmlFiles": number;
    "cssFiles": number;
    "javaScriptFiles": number;
    "luaFiles": number;
    "settingsFiles": number;
    "scriptFiles": number;

    /** Creates a new UIStats instance. */
    constructor($$source: Partial<UIStats> = {}) {
        if (!("htmlFiles" in $$source)) {
            this["htmlFiles"] = 0;
        }
        if (!("cssFiles" in $$source)) {
            this["cssFiles"] = 0;
        }
        if (!("javaScriptFiles" in $$source)) {
            this["javaScriptFiles"] = 0;
        }
        if (!("luaFiles" in $$source)) {
            this["luaFiles"] = 0;
        }
        if (!("settingsFiles" in $$source)) {
            this["settingsFiles"] = 0;
        }
        if (!("scriptFiles" in $$source)) {
            this["scriptFiles"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UIStats instance from a string or object.
     */
    static createFrom($$source: any = {}): UIStats {
        const $$createField0_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("appRoots" in $$parsedSource) {
            $$parsedSource["appRoots"] = $$createField0_0($$parsedSource["appRoots"]);
        }
        return new UIStats($$parsedSource as Partial<UIStats>);
    }
}

export class ValidationResult {
    "valid": boolean;
    "issues": Issue[];

    /** Creates a new ValidationResult instance. */
    constructor($$source: Partial<ValidationResult> = {}) {
        if (!("valid" in $$source)) {
            this["valid"] = false;
        }
        if (!("issues" in $$source)) {
            this["issues"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ValidationResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ValidationResult {
        const $$createField1_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("issues" in $$parsedSource) {
            $$parsedSource["issues"] = $$createField1_0($$parsedSource["issues"]);
        }
        return new ValidationResult($$parsedSource as Partial<ValidationResult>);
    }
}

export class Variant {
    "namespace": string;
    "baseName": string;
    "configPath": string;
    "metadataPath"?: string;
    "thumbnailPath"?: string;
    "configuration"?: string;
    "description"?: string;
    "configType"?: string;
    "bodyStyle"?: string;
    "drivetrain"?: string;
    "transmission"?: string;
    "fuelType"?: string;
    "propulsion"?: string;
    "power"?: number;
    "torque"?: number;
    "weight"?: number;
    "value"?: number;
    "topSpeed"?: number;
    "fields"?: { [_ in string]?: any };

    /** Creates a new Variant instance. */
    constructor($$source: Partial<Variant> = {}) {
        if (!("namespace" in $$source)) {
            this["namespace"] = "";
        }
        if (!("baseName" in $$source)) {
            this["baseName"] = "";
        }
        if (!("configPath" in $$source)) {
            this["configPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Variant instance from a string or object.
     */
    static createFrom($$source: any = {}): Variant {
        const $$createField18_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("fields" in $$parsedSource) {
            $$parsedSource["fields"] = $$createField18_0($$parsedSource["fields"]);
        }
        return new Variant($$parsedSource as Partial<Variant>);
    }
}

export class WorkspaceChange {
    "path": string;
    "type": string;
    "beforeSha"?: string;
    "afterSha"?: string;
    "sizeBytes"?: number;
    "textDiff"?: string;

    /** Creates a new WorkspaceChange instance. */
    constructor($$source: Partial<WorkspaceChange> = {}) {
        if (!("path" in $$source)) {
            this["path"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceChange instance from a string or object.
     */
    static createFrom($$source: any = {}): WorkspaceChange {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceChange($$parsedSource as Partial<WorkspaceChange>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $$createType0);
const $$createType2 = ArchiveMember.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = MetadataDocument.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ImageCandidate.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = Variant.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = JBeamStats.createFrom;
const $$createType11 = MapStats.createFrom;
const $$createType12 = UIStats.createFrom;
const $$createType13 = Issue.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $Create.Map($Create.Any, $Create.Any);
