// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface ArchiveMember {
    "path": string;
    "compressedBytes": number;
    "uncompressedBytes": number;
    "crc32": number;
    "method": number;
    "modifiedAt"?: string;
    "directory": boolean;
}

export interface ExportResult {
    "path": string;
    "sha256": string;
    "sizeBytes": number;
    "createdAt": string;
    "entryCount": number;
    "fingerprint": string;
}

export interface FileSnapshot {
    "path": string;
    "sha256": string;
    "sizeBytes": number;
    "modifiedNs": number;
}

export interface ImageCandidate {
    "path": string;
    "role": string;
    "uncompressedBytes": number;
    "width"?: number;
    "height"?: number;
    "mime"?: string;
    "assetId"?: string;
}

export interface Issue {
    "code": string;
    "severity": Severity;
    "message": string;
    "path"?: string;
}

export interface JBeamStats {
    "files": number;
    "parsedFiles": number;
    "declaredNodes": number;
    "declaredBeams": number;
    "declaredTriangles": number;
    "declaredSlots": number;
    "declaredHydros": number;
    "controllers"?: string[] | null;
}

export enum Kind {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    KindVehicle = "vehicle",
    KindMap = "map",
    KindUI = "ui",
    KindScript = "script",
    KindMixed = "mixed",
    KindUnknown = "unknown",
};

export interface Manifest {
    "schemaVersion": number;
    "analyzerVersion": string;
    "analyzedAt": string;
    "archivePath": string;
    "filename": string;
    "sizeBytes": number;
    "modifiedAt": string;
    "centralFingerprint": string;
    "fullSha256"?: string;
    "validArchive": boolean;
    "wrapper"?: string;
    "kind": Kind;
    "contentTags"?: string[] | null;
    "namespaces": { [_ in string]?: string[] | null } | null;
    "title"?: string;
    "description"?: string;
    "author"?: string;
    "version"?: string;
    "entryCount": number;
    "compressedBytes": number;
    "uncompressedBytes": number;
    "members": ArchiveMember[] | null;
    "metadataDocuments"?: MetadataDocument[] | null;
    "images"?: ImageCandidate[] | null;
    "selectedImagePath"?: string;
    "variants"?: Variant[] | null;
    "jbeam": JBeamStats;
    "map": MapStats;
    "ui": UIStats;
    "sharedAssets"?: SharedAssetStats | null;
    "issues"?: Issue[] | null;
}

export interface MapStats {
    "levelIds"?: string[] | null;
    "terrainFiles": number;
    "levelObjectFiles": number;
    "forestFiles": number;
    "facilityFiles": number;
    "materialFiles": number;
    "modelFiles": number;
    "textureFiles": number;
    "spawnPoints": number;
}

export interface MetadataDocument {
    "path": string;
    "data": { [_ in string]?: any } | null;
}

export enum Severity {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    SeverityInfo = "info",
    SeverityWarning = "warning",
    SeverityError = "error",
};

export interface SharedAssetStats {
    "files": number;
}

export interface UIStats {
    "appRoots"?: string[] | null;
    "htmlFiles": number;
    "cssFiles": number;
    "javaScriptFiles": number;
    "luaFiles": number;
    "settingsFiles": number;
    "scriptFiles": number;
}

export interface ValidationResult {
    "valid": boolean;
    "issues": Issue[] | null;
}

export interface Variant {
    "namespace": string;
    "baseName": string;
    "configPath": string;
    "metadataPath"?: string;
    "thumbnailPath"?: string;
    "configuration"?: string;
    "description"?: string;
    "configType"?: string;
    "bodyStyle"?: string;
    "drivetrain"?: string;
    "transmission"?: string;
    "fuelType"?: string;
    "propulsion"?: string;
    "power"?: number;
    "torque"?: number;
    "weight"?: number;
    "value"?: number;
    "topSpeed"?: number;
    "fields"?: { [_ in string]?: any } | null;
}

export interface WorkspaceChange {
    "path": string;
    "type": string;
    "beforeSha"?: string;
    "afterSha"?: string;
    "sizeBytes"?: number;
    "textDiff"?: string;
}
