//@ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as main$0 from "../../../../SignedAdam/beamng-mod-studio/models.js";

function configure() {
    Object.freeze(Object.assign($Create.Events, {
        "agent:event": $$createType0,
        "library:item": $$createType1,
        "library:scan": $$createType2,
    }));
}

// Private type creation functions
const $$createType0 = main$0.AgentActivity.createFrom;
const $$createType1 = main$0.LibraryItem.createFrom;
const $$createType2 = main$0.ScanProgress.createFrom;

configure();
