// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type { Events } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import type * as main$0 from "../../../../SignedAdam/beamng-mod-studio/models.js";

declare module "@wailsio/runtime" {
    namespace Events {
        interface CustomEvents {
            "agent:event": main$0.AgentActivity;
            "ai:connection": main$0.AIConnectionEvent;
            "game:status": main$0.GameStatus;
            "library:item": main$0.LibraryItem;
            "library:scan": main$0.ScanProgress;
            "mod:library": main$0.LibraryUpdateEvent;
            "mods:detected": main$0.NewModsReview;
            "play:progress": main$0.PlayProgress;
            "storage:progress": main$0.StorageProgress;
            "virus:scan": main$0.VirusScanProgress;
        }
    }
}
