// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modkit$0 from "../beamworlds-modkit/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AIUsage(): $CancellablePromise<$models.AIUsage> {
    return $Call.ByID(1900328351);
}

export function ActivateProfile(profileID: string): $CancellablePromise<$models.ProfileActivation> {
    return $Call.ByID(3464844020, profileID);
}

export function AnalyzeRuntime(workspaceID: string): $CancellablePromise<$models.RuntimeReport> {
    return $Call.ByID(2967954498, workspaceID);
}

export function CancelScan(): $CancellablePromise<boolean> {
    return $Call.ByID(2524160225);
}

export function CloneVehicleVariant(workspaceID: string, sourceConfigPath: string, newBaseName: string, displayName: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(362672790, workspaceID, sourceConfigPath, newBaseName, displayName);
}

export function Config(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(91484996);
}

export function CreateLibraryFolder(name: string, parentID: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(3930565201, name, parentID);
}

export function CreateNewMod(request: $models.NewModRequest): $CancellablePromise<$models.WorkspaceDetail> {
    return $Call.ByID(3533916892, request);
}

export function CreatePreset(name: string, description: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(2670900301, name, description);
}

export function CreateProfile(name: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(1028333027, name);
}

export function CreateWorkspace(entityID: string): $CancellablePromise<$models.WorkspaceDetail> {
    return $Call.ByID(771272559, entityID);
}

export function CreateWorkspaceDirectory(workspaceID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(1435817446, workspaceID, relativePath);
}

export function Dashboard(): $CancellablePromise<$models.Dashboard> {
    return $Call.ByID(2982594826);
}

export function DeleteLibraryFolder(folderID: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(1596845892, folderID);
}

export function DeletePreset(presetID: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(4039770734, presetID);
}

export function DeleteProfile(profileID: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(1212961758, profileID);
}

export function DeleteWorkspaceDraft(workspaceID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(2433899589, workspaceID, relativePath);
}

export function DeleteWorkspacePath(workspaceID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(1820792685, workspaceID, relativePath);
}

export function ExportWorkspace(workspaceID: string, label: string): $CancellablePromise<$models.ExportResponse> {
    return $Call.ByID(2564207477, workspaceID, label);
}

export function FollowUpModAudit(entityID: string, paths: string[] | null, question: string): $CancellablePromise<$models.ModAudit> {
    return $Call.ByID(3975895313, entityID, paths, question);
}

export function GetEntity(entityID: string): $CancellablePromise<$models.EntityDetail> {
    return $Call.ByID(2226382837, entityID);
}

export function GetKnowledge(entityID: string): $CancellablePromise<$models.KnowledgeDocument[] | null> {
    return $Call.ByID(1016561506, entityID);
}

export function GetModAudit(entityID: string): $CancellablePromise<$models.ModAudit> {
    return $Call.ByID(3934379141, entityID);
}

export function GetPreset(presetID: string): $CancellablePromise<$models.PresetDetail> {
    return $Call.ByID(1199600373, presetID);
}

export function GetProfile(profileID: string): $CancellablePromise<$models.ProfileDetail> {
    return $Call.ByID(3217990731, profileID);
}

export function GetSetupState(): $CancellablePromise<$models.SetupState> {
    return $Call.ByID(2012181732);
}

export function GetWorkspace(workspaceID: string): $CancellablePromise<$models.WorkspaceDetail> {
    return $Call.ByID(1349316807, workspaceID);
}

export function HasAppliedModProfile(): $CancellablePromise<boolean> {
    return $Call.ByID(2187128874);
}

export function InstallExportForTest(workspaceID: string, exportID: string): $CancellablePromise<$models.TestInstallRecord> {
    return $Call.ByID(2477417930, workspaceID, exportID);
}

export function LaunchBeamNG(workspaceID: string): $CancellablePromise<$models.ProcessLaunch> {
    return $Call.ByID(4029943113, workspaceID);
}

export function LaunchProfile(profileID: string): $CancellablePromise<$models.ProfileLaunch> {
    return $Call.ByID(2498686646, profileID);
}

export function ListAgentEvents(runID: string): $CancellablePromise<$models.AgentEventRecord[] | null> {
    return $Call.ByID(2949754262, runID);
}

export function ListAgentModels(): $CancellablePromise<$models.AgentModelOption[] | null> {
    return $Call.ByID(1394913177);
}

export function ListAgentRuns(workspaceID: string): $CancellablePromise<$models.AgentRunRecord[] | null> {
    return $Call.ByID(2006466853, workspaceID);
}

export function ListLibrary(status: string, kind: string, query: string, folderID: string): $CancellablePromise<$models.LibraryItem[] | null> {
    return $Call.ByID(621180473, status, kind, query, folderID);
}

export function ListWorkspaces(): $CancellablePromise<$models.WorkspaceRecord[] | null> {
    return $Call.ByID(350918204);
}

export function MoveLibraryItem(entityID: string, folderID: string): $CancellablePromise<void> {
    return $Call.ByID(1278964353, entityID, folderID);
}

export function OpenGameDirectory(): $CancellablePromise<void> {
    return $Call.ByID(565250723);
}

export function Organization(): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(3433886317);
}

export function PickDirectory(title: string, initialDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(4292351642, title, initialDirectory);
}

export function ReadWorkspaceFile(workspaceID: string, relativePath: string): $CancellablePromise<$models.WorkspaceTextFile> {
    return $Call.ByID(3870910925, workspaceID, relativePath);
}

export function RenameLibraryFolder(folderID: string, name: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(2740790923, folderID, name);
}

export function RenameProfile(profileID: string, name: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(1831808545, profileID, name);
}

export function RenameWorkspacePath(workspaceID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(2387663450, workspaceID, oldPath, newPath);
}

export function RestartApplication(): $CancellablePromise<void> {
    return $Call.ByID(2071406909);
}

export function RestoreNormalModSelection(): $CancellablePromise<void> {
    return $Call.ByID(58419305);
}

export function RevealWorkspacePath(workspaceID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(878556355, workspaceID, relativePath);
}

export function RunModAuditFull(entityID: string): $CancellablePromise<$models.ModAudit> {
    return $Call.ByID(1445065873, entityID);
}

export function RunModAuditLocal(entityID: string): $CancellablePromise<$models.ModAudit> {
    return $Call.ByID(487750775, entityID);
}

export function RunModAuditPreScan(entityID: string): $CancellablePromise<$models.ModAudit> {
    return $Call.ByID(1673988696, entityID);
}

export function SaveSettings(update: $models.SettingsUpdate): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3784651466, update);
}

export function SaveSetup(input: $models.SetupInput): $CancellablePromise<$models.SetupResult> {
    return $Call.ByID(654217000, input);
}

export function SaveWorkspaceDraft(workspaceID: string, relativePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(4251899839, workspaceID, relativePath, content);
}

export function ScanLibrary(): $CancellablePromise<$models.ScanSummary> {
    return $Call.ByID(1511987522);
}

export function SearchWorkspace(workspaceID: string, query: string, maxResults: number): $CancellablePromise<string[] | null> {
    return $Call.ByID(2068548899, workspaceID, query, maxResults);
}

export function SetPresetMod(presetID: string, entityID: string, included: boolean): $CancellablePromise<void> {
    return $Call.ByID(1960851151, presetID, entityID, included);
}

export function SetProfileMod(profileID: string, entityID: string, included: boolean): $CancellablePromise<void> {
    return $Call.ByID(2912892229, profileID, entityID, included);
}

export function SetProfilePreset(profileID: string, presetID: string, selected: boolean): $CancellablePromise<void> {
    return $Call.ByID(3296916816, profileID, presetID, selected);
}

export function SetWorkspaceJSONValue(workspaceID: string, relativePath: string, dottedPath: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(195891334, workspaceID, relativePath, dottedPath, value);
}

export function Settings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3630548879);
}

export function StartAgent(workspaceID: string, prompt: string, modelOverride: string): $CancellablePromise<$models.AgentRunRecord> {
    return $Call.ByID(3564943239, workspaceID, prompt, modelOverride);
}

export function StopAgent(runID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1641704647, runID);
}

export function UninstallTest(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(3380044888, workspaceID);
}

export function UpdatePreset(presetID: string, name: string, description: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(2558523108, presetID, name, description);
}

export function ValidateWorkspace(workspaceID: string): $CancellablePromise<modkit$0.ValidationResult> {
    return $Call.ByID(1665736785, workspaceID);
}

export function WorkspaceDiff(workspaceID: string): $CancellablePromise<modkit$0.WorkspaceChange[] | null> {
    return $Call.ByID(1837507304, workspaceID);
}

export function WriteWorkspaceFile(workspaceID: string, relativePath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1515493856, workspaceID, relativePath, content);
}
