// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modkit$0 from "../beamworlds-modkit/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<$models.AIUsage>}
 */
export function AIUsage() {
    return $Call.ByID(1900328351).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * @param {string} profileID
 * @returns {$CancellablePromise<$models.ProfileActivation>}
 */
export function ActivateProfile(profileID) {
    return $Call.ByID(3464844020, profileID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<$models.RuntimeReport>}
 */
export function AnalyzeRuntime(workspaceID) {
    return $Call.ByID(2967954498, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * @returns {$CancellablePromise<boolean>}
 */
export function CancelScan() {
    return $Call.ByID(2524160225);
}

/**
 * @param {string} workspaceID
 * @param {string} sourceConfigPath
 * @param {string} newBaseName
 * @param {string} displayName
 * @returns {$CancellablePromise<string[]>}
 */
export function CloneVehicleVariant(workspaceID, sourceConfigPath, newBaseName, displayName) {
    return $Call.ByID(362672790, workspaceID, sourceConfigPath, newBaseName, displayName).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AppConfig>}
 */
export function Config() {
    return $Call.ByID(91484996).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * @param {string} name
 * @param {string} parentID
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function CreateLibraryFolder(name, parentID) {
    return $Call.ByID(3930565201, name, parentID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {$models.NewModRequest} request
 * @returns {$CancellablePromise<$models.WorkspaceDetail>}
 */
export function CreateNewMod(request) {
    return $Call.ByID(3533916892, request).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function CreatePreset(name, description) {
    return $Call.ByID(2670900301, name, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} name
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function CreateProfile(name) {
    return $Call.ByID(1028333027, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} entityID
 * @returns {$CancellablePromise<$models.WorkspaceDetail>}
 */
export function CreateWorkspace(entityID) {
    return $Call.ByID(771272559, entityID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} relativePath
 * @returns {$CancellablePromise<void>}
 */
export function CreateWorkspaceDirectory(workspaceID, relativePath) {
    return $Call.ByID(1435817446, workspaceID, relativePath);
}

/**
 * @returns {$CancellablePromise<$models.Dashboard>}
 */
export function Dashboard() {
    return $Call.ByID(2982594826).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * @param {string} folderID
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function DeleteLibraryFolder(folderID) {
    return $Call.ByID(1596845892, folderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} presetID
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function DeletePreset(presetID) {
    return $Call.ByID(4039770734, presetID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} profileID
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function DeleteProfile(profileID) {
    return $Call.ByID(1212961758, profileID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} relativePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorkspaceDraft(workspaceID, relativePath) {
    return $Call.ByID(2433899589, workspaceID, relativePath);
}

/**
 * @param {string} workspaceID
 * @param {string} relativePath
 * @returns {$CancellablePromise<void>}
 */
export function DeleteWorkspacePath(workspaceID, relativePath) {
    return $Call.ByID(1820792685, workspaceID, relativePath);
}

/**
 * @param {string} workspaceID
 * @param {string} label
 * @returns {$CancellablePromise<$models.ExportResponse>}
 */
export function ExportWorkspace(workspaceID, label) {
    return $Call.ByID(2564207477, workspaceID, label).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * @param {string} entityID
 * @returns {$CancellablePromise<$models.EntityDetail>}
 */
export function GetEntity(entityID) {
    return $Call.ByID(2226382837, entityID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * @param {string} entityID
 * @returns {$CancellablePromise<$models.KnowledgeDocument[]>}
 */
export function GetKnowledge(entityID) {
    return $Call.ByID(1016561506, entityID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @param {string} presetID
 * @returns {$CancellablePromise<$models.PresetDetail>}
 */
export function GetPreset(presetID) {
    return $Call.ByID(1199600373, presetID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType12($result);
    }));
}

/**
 * @param {string} profileID
 * @returns {$CancellablePromise<$models.ProfileDetail>}
 */
export function GetProfile(profileID) {
    return $Call.ByID(3217990731, profileID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<$models.WorkspaceDetail>}
 */
export function GetWorkspace(workspaceID) {
    return $Call.ByID(1349316807, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} exportID
 * @returns {$CancellablePromise<$models.TestInstallRecord>}
 */
export function InstallExportForTest(workspaceID, exportID) {
    return $Call.ByID(2477417930, workspaceID, exportID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<$models.ProcessLaunch>}
 */
export function LaunchBeamNG(workspaceID) {
    return $Call.ByID(4029943113, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * @param {string} profileID
 * @returns {$CancellablePromise<$models.ProfileLaunch>}
 */
export function LaunchProfile(profileID) {
    return $Call.ByID(2498686646, profileID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<$models.AgentEventRecord[]>}
 */
export function ListAgentEvents(runID) {
    return $Call.ByID(2949754262, runID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.AgentModelOption[]>}
 */
export function ListAgentModels() {
    return $Call.ByID(1394913177).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<$models.AgentRunRecord[]>}
 */
export function ListAgentRuns(workspaceID) {
    return $Call.ByID(2006466853, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * @param {string} status
 * @param {string} kind
 * @param {string} query
 * @param {string} folderID
 * @returns {$CancellablePromise<$models.LibraryItem[]>}
 */
export function ListLibrary(status, kind, query, folderID) {
    return $Call.ByID(621180473, status, kind, query, folderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * @returns {$CancellablePromise<$models.WorkspaceRecord[]>}
 */
export function ListWorkspaces() {
    return $Call.ByID(350918204).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * @param {string} entityID
 * @param {string} folderID
 * @returns {$CancellablePromise<void>}
 */
export function MoveLibraryItem(entityID, folderID) {
    return $Call.ByID(1278964353, entityID, folderID);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function OpenGameDirectory() {
    return $Call.ByID(565250723);
}

/**
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function Organization() {
    return $Call.ByID(3433886317).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} relativePath
 * @returns {$CancellablePromise<$models.WorkspaceTextFile>}
 */
export function ReadWorkspaceFile(workspaceID, relativePath) {
    return $Call.ByID(3870910925, workspaceID, relativePath).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType27($result);
    }));
}

/**
 * @param {string} folderID
 * @param {string} name
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function RenameLibraryFolder(folderID, name) {
    return $Call.ByID(2740790923, folderID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} profileID
 * @param {string} name
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function RenameProfile(profileID, name) {
    return $Call.ByID(1831808545, profileID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} oldPath
 * @param {string} newPath
 * @returns {$CancellablePromise<void>}
 */
export function RenameWorkspacePath(workspaceID, oldPath, newPath) {
    return $Call.ByID(2387663450, workspaceID, oldPath, newPath);
}

/**
 * @param {$models.SettingsUpdate} update
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function SaveSettings(update) {
    return $Call.ByID(3784651466, update).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} relativePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function SaveWorkspaceDraft(workspaceID, relativePath, content) {
    return $Call.ByID(4251899839, workspaceID, relativePath, content);
}

/**
 * @returns {$CancellablePromise<$models.ScanSummary>}
 */
export function ScanLibrary() {
    return $Call.ByID(1511987522).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} query
 * @param {number} maxResults
 * @returns {$CancellablePromise<string[]>}
 */
export function SearchWorkspace(workspaceID, query, maxResults) {
    return $Call.ByID(2068548899, workspaceID, query, maxResults).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * @param {string} presetID
 * @param {string} entityID
 * @param {boolean} included
 * @returns {$CancellablePromise<void>}
 */
export function SetPresetMod(presetID, entityID, included) {
    return $Call.ByID(1960851151, presetID, entityID, included);
}

/**
 * @param {string} profileID
 * @param {string} entityID
 * @param {boolean} included
 * @returns {$CancellablePromise<void>}
 */
export function SetProfileMod(profileID, entityID, included) {
    return $Call.ByID(2912892229, profileID, entityID, included);
}

/**
 * @param {string} profileID
 * @param {string} presetID
 * @param {boolean} selected
 * @returns {$CancellablePromise<void>}
 */
export function SetProfilePreset(profileID, presetID, selected) {
    return $Call.ByID(3296916816, profileID, presetID, selected);
}

/**
 * @param {string} workspaceID
 * @param {string} relativePath
 * @param {string} dottedPath
 * @param {any} value
 * @returns {$CancellablePromise<void>}
 */
export function SetWorkspaceJSONValue(workspaceID, relativePath, dottedPath, value) {
    return $Call.ByID(195891334, workspaceID, relativePath, dottedPath, value);
}

/**
 * @returns {$CancellablePromise<$models.AppSettings>}
 */
export function Settings() {
    return $Call.ByID(3630548879).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} prompt
 * @param {string} modelOverride
 * @returns {$CancellablePromise<$models.AgentRunRecord>}
 */
export function StartAgent(workspaceID, prompt, modelOverride) {
    return $Call.ByID(3564943239, workspaceID, prompt, modelOverride).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * @param {string} runID
 * @returns {$CancellablePromise<boolean>}
 */
export function StopAgent(runID) {
    return $Call.ByID(1641704647, runID);
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<void>}
 */
export function UninstallTest(workspaceID) {
    return $Call.ByID(3380044888, workspaceID);
}

/**
 * @param {string} presetID
 * @param {string} name
 * @param {string} description
 * @returns {$CancellablePromise<$models.OrganizationState>}
 */
export function UpdatePreset(presetID, name, description) {
    return $Call.ByID(2558523108, presetID, name, description).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<modkit$0.ValidationResult>}
 */
export function ValidateWorkspace(workspaceID) {
    return $Call.ByID(1665736785, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType30($result);
    }));
}

/**
 * @param {string} workspaceID
 * @returns {$CancellablePromise<modkit$0.WorkspaceChange[]>}
 */
export function WorkspaceDiff(workspaceID) {
    return $Call.ByID(1837507304, workspaceID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType32($result);
    }));
}

/**
 * @param {string} workspaceID
 * @param {string} relativePath
 * @param {string} content
 * @returns {$CancellablePromise<void>}
 */
export function WriteWorkspaceFile(workspaceID, relativePath, content) {
    return $Call.ByID(1515493856, workspaceID, relativePath, content);
}

// Private type creation functions
const $$createType0 = $models.AIUsage.createFrom;
const $$createType1 = $models.ProfileActivation.createFrom;
const $$createType2 = $models.RuntimeReport.createFrom;
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = $models.AppConfig.createFrom;
const $$createType5 = $models.OrganizationState.createFrom;
const $$createType6 = $models.WorkspaceDetail.createFrom;
const $$createType7 = $models.Dashboard.createFrom;
const $$createType8 = $models.ExportResponse.createFrom;
const $$createType9 = $models.EntityDetail.createFrom;
const $$createType10 = $models.KnowledgeDocument.createFrom;
const $$createType11 = $Create.Array($$createType10);
const $$createType12 = $models.PresetDetail.createFrom;
const $$createType13 = $models.ProfileDetail.createFrom;
const $$createType14 = $models.TestInstallRecord.createFrom;
const $$createType15 = $models.ProcessLaunch.createFrom;
const $$createType16 = $models.ProfileLaunch.createFrom;
const $$createType17 = $models.AgentEventRecord.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = $models.AgentModelOption.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = $models.AgentRunRecord.createFrom;
const $$createType22 = $Create.Array($$createType21);
const $$createType23 = $models.LibraryItem.createFrom;
const $$createType24 = $Create.Array($$createType23);
const $$createType25 = $models.WorkspaceRecord.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = $models.WorkspaceTextFile.createFrom;
const $$createType28 = $models.AppSettings.createFrom;
const $$createType29 = $models.ScanSummary.createFrom;
const $$createType30 = modkit$0.ValidationResult.createFrom;
const $$createType31 = modkit$0.WorkspaceChange.createFrom;
const $$createType32 = $Create.Array($$createType31);
