// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modkit$0 from "../beamworlds-modkit/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AIConnections(): $CancellablePromise<$models.AIConnectionState> {
    return $Call.ByID(3088172393);
}

export function AIUsage(): $CancellablePromise<$models.AIUsage> {
    return $Call.ByID(1900328351);
}

export function AnalyzeRuntime(workspaceID: string): $CancellablePromise<$models.RuntimeReport> {
    return $Call.ByID(2967954498, workspaceID);
}

/**
 * CacheModArtwork extracts one discovered image through modkit's bounded ZIP
 * reader and registers the content-addressed file in the existing asset cache.
 * The operation never changes collection membership or the mod's selected
 * thumbnail.
 */
export function CacheModArtwork(entityID: string, memberPath: string): $CancellablePromise<$models.CollectionCoverImage> {
    return $Call.ByID(3126905308, entityID, memberPath);
}

export function CancelAIConnection(loginID: string): $CancellablePromise<void> {
    return $Call.ByID(1418849106, loginID);
}

/**
 * CancelGitHubPublish cancels without waiting for the workspace mutation
 * mutex, allowing a blocked or transferring operation to observe cancellation.
 */
export function CancelGitHubPublish(operationID: string): $CancellablePromise<$models.GitHubPublishOperation> {
    return $Call.ByID(383093918, operationID);
}

/**
 * CancelGitHubPublishAuth cancels the device flow and wipes transient secrets.
 */
export function CancelGitHubPublishAuth(sessionID: string): $CancellablePromise<$models.GitHubPublishAuthSession> {
    return $Call.ByID(1641969844, sessionID);
}

export function CancelScan(): $CancellablePromise<boolean> {
    return $Call.ByID(2524160225);
}

export function CancelWorkspaceGitOperation(workspaceID: string): $CancellablePromise<boolean> {
    return $Call.ByID(2670872, workspaceID);
}

/**
 * ClearGitHubPublishSession wipes the in-memory authentication/session state.
 */
export function ClearGitHubPublishSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(3989810141, sessionID);
}

export function CloneVehicleVariant(workspaceID: string, sourceConfigPath: string, newBaseName: string, displayName: string): $CancellablePromise<string[] | null> {
    return $Call.ByID(362672790, workspaceID, sourceConfigPath, newBaseName, displayName);
}

export function CommitWorkspaceGit(workspaceID: string, message: string, amend: boolean, expectedFingerprint: string): $CancellablePromise<$models.GitCommitResult> {
    return $Call.ByID(896073316, workspaceID, message, amend, expectedFingerprint);
}

export function Config(): $CancellablePromise<$models.AppConfig> {
    return $Call.ByID(91484996);
}

export function ConfigureWorkspaceVirgil(workspaceID: string, enabled: boolean): $CancellablePromise<$models.WorkspaceDetail> {
    return $Call.ByID(1209241224, workspaceID, enabled);
}

export function CreateCollection(name: string, description: string, parentID: string): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(2008347414, name, description, parentID);
}

export function CreateModTag(name: string, color: string, icon: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(1759538554, name, color, icon);
}

export function CreateNewMod(request: $models.NewModRequest): $CancellablePromise<$models.WorkspaceDetail> {
    return $Call.ByID(3533916892, request);
}

export function CreatePlayProfile(collectionIDs: string[] | null): $CancellablePromise<$models.ModProfile> {
    return $Call.ByID(728524565, collectionIDs);
}

export function CreateWorkspace(entityID: string): $CancellablePromise<$models.WorkspaceDetail> {
    return $Call.ByID(771272559, entityID);
}

export function CreateWorkspaceDirectory(workspaceID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(1435817446, workspaceID, relativePath);
}

export function CreateWorkspaceGitBranch(workspaceID: string, name: string, startPoint: string, expectedFingerprint: string): $CancellablePromise<$models.GitStatus> {
    return $Call.ByID(3841605845, workspaceID, name, startPoint, expectedFingerprint);
}

export function Dashboard(): $CancellablePromise<$models.Dashboard> {
    return $Call.ByID(2982594826);
}

export function DeleteArchiveFiles(linkIDs: string[] | null): $CancellablePromise<$models.ModRemovalResult> {
    return $Call.ByID(354172320, linkIDs);
}

export function DeleteCollections(collectionIDs: string[] | null): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(4193965494, collectionIDs);
}

/**
 * DeleteModArchives recycles each archive and then forgets the mod. A mod whose
 * archive could not be recycled stays in the library: the index must never
 * claim a file is gone while it is still on disk.
 */
export function DeleteModArchives(entityIDs: string[] | null): $CancellablePromise<$models.ModRemovalResult> {
    return $Call.ByID(3170877512, entityIDs);
}

export function DeleteModTag(tagID: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(1455379505, tagID);
}

export function DeletePlayProfile(profileID: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(1330165372, profileID);
}

export function DeleteWorkspaceDraft(workspaceID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(2433899589, workspaceID, relativePath);
}

export function DeleteWorkspacePath(workspaceID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(1820792685, workspaceID, relativePath);
}

export function DiscardWorkspaceGitPaths(workspaceID: string, paths: string[] | null, expectedFingerprint: string): $CancellablePromise<$models.GitDiscardResult> {
    return $Call.ByID(1065278057, workspaceID, paths, expectedFingerprint);
}

/**
 * DismissModFamily records the current membership signature for one family.
 * The raw family set is used for lookup so dismissing an already dismissed
 * family remains idempotent.
 */
export function DismissModFamily(familyID: string): $CancellablePromise<$models.ModFamily[] | null> {
    return $Call.ByID(3185854118, familyID);
}

export function DuplicateCollection(collectionID: string): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(1225056835, collectionID);
}

export function EntityPreviewCandidates(entityID: string): $CancellablePromise<$models.EntityPreviewCandidate[] | null> {
    return $Call.ByID(193290949, entityID);
}

export function ExportWorkspace(workspaceID: string, label: string): $CancellablePromise<$models.ExportResponse> {
    return $Call.ByID(2564207477, workspaceID, label);
}

export function ExtractLibraryArchiveMember(entityID: string, memberPath: string): $CancellablePromise<string> {
    return $Call.ByID(3883547530, entityID, memberPath);
}

export function FetchWorkspaceGit(workspaceID: string): $CancellablePromise<$models.GitOperationResult> {
    return $Call.ByID(1377658117, workspaceID);
}

export function FileManagerActionLabel(): $CancellablePromise<string> {
    return $Call.ByID(3849000745);
}

/**
 * ForgetMods removes the mods from the index without touching a single file.
 */
export function ForgetMods(entityIDs: string[] | null): $CancellablePromise<$models.ModRemovalResult> {
    return $Call.ByID(2057459022, entityIDs);
}

export function ForgetVirgilSession(sessionID: string): $CancellablePromise<void> {
    return $Call.ByID(2373891276, sessionID);
}

export function GetCollection(collectionID: string): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(116408958, collectionID);
}

export function GetCollectionDeleteImpact(collectionIDs: string[] | null): $CancellablePromise<$models.CollectionUsage> {
    return $Call.ByID(1777098539, collectionIDs);
}

export function GetEntity(entityID: string): $CancellablePromise<$models.EntityDetail> {
    return $Call.ByID(2226382837, entityID);
}

/**
 * GetGitHubPublishOperation polls an asynchronous operation/result.
 */
export function GetGitHubPublishOperation(operationID: string): $CancellablePromise<$models.GitHubPublishOperation> {
    return $Call.ByID(1287636273, operationID);
}

export function GetKnowledge(entityID: string): $CancellablePromise<$models.KnowledgeDocument[] | null> {
    return $Call.ByID(1016561506, entityID);
}

/**
 * GetModArtwork returns every bounded image candidate discovered while the
 * archive was indexed. Candidates are intentionally returned without reading
 * archive members; only assets already present in the cache get a URL.
 */
export function GetModArtwork(entityID: string): $CancellablePromise<$models.CollectionArtworkCandidate[] | null> {
    return $Call.ByID(3787696818, entityID);
}

export function GetPlayRuntimeState(): $CancellablePromise<$models.PlayRuntimeState> {
    return $Call.ByID(640169425);
}

export function GetPlayState(): $CancellablePromise<$models.PlayState> {
    return $Call.ByID(2807498781);
}

export function GetSetupState(): $CancellablePromise<$models.SetupState> {
    return $Call.ByID(2012181732);
}

export function GetWorkspace(workspaceID: string): $CancellablePromise<$models.WorkspaceDetail> {
    return $Call.ByID(1349316807, workspaceID);
}

export function GetWorkspaceGitDiff(workspaceID: string, relativePath: string, comparison: string): $CancellablePromise<$models.GitDiff> {
    return $Call.ByID(1165261618, workspaceID, relativePath, comparison);
}

export function GetWorkspaceGitStatus(workspaceID: string): $CancellablePromise<$models.GitStatus> {
    return $Call.ByID(1546873591, workspaceID);
}

/**
 * GitHubPublishConfiguration reports non-secret OAuth App setup.
 */
export function GitHubPublishConfiguration(): $CancellablePromise<$models.GitHubPublishConfiguration> {
    return $Call.ByID(2877149206);
}

export function InstallExportForTest(workspaceID: string, exportID: string): $CancellablePromise<$models.TestInstallRecord> {
    return $Call.ByID(2477417930, workspaceID, exportID);
}

export function LaunchBeamNG(workspaceID: string): $CancellablePromise<$models.ProcessLaunch> {
    return $Call.ByID(4029943113, workspaceID);
}

export function LaunchPlaySelection(request: $models.PlayRequest): $CancellablePromise<$models.PlayResult> {
    return $Call.ByID(3098743839, request);
}

export function ListAgentEvents(runID: string): $CancellablePromise<$models.AgentEventRecord[] | null> {
    return $Call.ByID(2949754262, runID);
}

export function ListAgentModels(): $CancellablePromise<$models.AgentModelOption[] | null> {
    return $Call.ByID(1394913177);
}

export function ListLibrary(health: string, kind: string, query: string, collectionID: string): $CancellablePromise<$models.LibraryItem[] | null> {
    return $Call.ByID(621180473, health, kind, query, collectionID);
}

export function ListVirusScans(entityID: string): $CancellablePromise<$models.VirusScanRun[] | null> {
    return $Call.ByID(652516587, entityID);
}

export function ListWorkspaceGitBranches(workspaceID: string): $CancellablePromise<$models.GitBranch[] | null> {
    return $Call.ByID(1681566641, workspaceID);
}

export function ListWorkspaces(): $CancellablePromise<$models.WorkspaceRecord[] | null> {
    return $Call.ByID(350918204);
}

/**
 * ModFamilies returns every currently visible family. The computation is kept
 * in the store so the service method remains the same thin Wails boundary as
 * the other library APIs.
 */
export function ModFamilies(): $CancellablePromise<$models.ModFamily[] | null> {
    return $Call.ByID(3872770186);
}

export function OpenGameDirectory(): $CancellablePromise<void> {
    return $Call.ByID(565250723);
}

/**
 * Organization exposes the unified collection graph, tags, and saved Play
 * profiles. Folders, presets, and private profile defaults are intentionally
 * not part of the live API after the organization migration.
 */
export function Organization(): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(3433886317);
}

export function PickDirectory(title: string, initialDirectory: string): $CancellablePromise<string> {
    return $Call.ByID(4292351642, title, initialDirectory);
}

export function PlanArchiveFileRemoval(linkIDs: string[] | null): $CancellablePromise<$models.ArchiveFileRemovalImpact> {
    return $Call.ByID(1157346201, linkIDs);
}

export function PlanModRemoval(entityIDs: string[] | null): $CancellablePromise<$models.ModRemovalImpact> {
    return $Call.ByID(627688409, entityIDs);
}

/**
 * PollGitHubPublishAuth performs at most one protocol-compliant device poll.
 */
export function PollGitHubPublishAuth(sessionID: string): $CancellablePromise<$models.GitHubPublishAuthSession> {
    return $Call.ByID(567328013, sessionID);
}

/**
 * PreflightGitHubPublish validates local Git and reads the GitHub target. It
 * performs no repository creation or local remote mutation.
 */
export function PreflightGitHubPublish(workspaceID: string, draft: $models.GitHubPublishDraft): $CancellablePromise<$models.GitHubPublishPreflight> {
    return $Call.ByID(2335916509, workspaceID, draft);
}

export function PreviewLibraryArchiveMember(entityID: string, memberPath: string): $CancellablePromise<$models.ArchiveMemberPreview | null> {
    return $Call.ByID(1766868719, entityID, memberPath);
}

export function PullWorkspaceGit(workspaceID: string, expectedFingerprint: string): $CancellablePromise<$models.GitOperationResult> {
    return $Call.ByID(2006851778, workspaceID, expectedFingerprint);
}

export function PushWorkspaceGit(workspaceID: string): $CancellablePromise<$models.GitOperationResult> {
    return $Call.ByID(4282287097, workspaceID);
}

export function ReadWorkspaceFile(workspaceID: string, relativePath: string): $CancellablePromise<$models.WorkspaceTextFile> {
    return $Call.ByID(3870910925, workspaceID, relativePath);
}

export function RenameModTag(tagID: string, name: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(3546457432, tagID, name);
}

export function RenamePlayProfile(profileID: string, name: string): $CancellablePromise<$models.ModProfile> {
    return $Call.ByID(3391840099, profileID, name);
}

export function RenameVirgilSession(sessionID: string, title: string): $CancellablePromise<$models.VirgilSessionRecord> {
    return $Call.ByID(466550229, sessionID, title);
}

export function RenameWorkspacePath(workspaceID: string, oldPath: string, newPath: string): $CancellablePromise<void> {
    return $Call.ByID(2387663450, workspaceID, oldPath, newPath);
}

export function ReorderCollectionMembers(collectionID: string, entityIDs: string[] | null, childIDs: string[] | null): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(937529560, collectionID, entityIDs, childIDs);
}

export function ResetEntityPreview(entityID: string): $CancellablePromise<$models.LibraryItem> {
    return $Call.ByID(3865490126, entityID);
}

export function ResolvePlaySelection(collectionIDs: string[] | null): $CancellablePromise<$models.PlaySelection> {
    return $Call.ByID(2225443946, collectionIDs);
}

export function RestartApplication(): $CancellablePromise<void> {
    return $Call.ByID(2071406909);
}

export function ResumeVirgilSession(sessionID: string): $CancellablePromise<$models.VirgilSessionRecord> {
    return $Call.ByID(2325737482, sessionID);
}

export function RevealLibraryArchive(entityID: string): $CancellablePromise<void> {
    return $Call.ByID(3289149128, entityID);
}

export function RevealWorkspacePath(workspaceID: string, relativePath: string): $CancellablePromise<void> {
    return $Call.ByID(878556355, workspaceID, relativePath);
}

export function RunVirusScan(entityID: string, mode: string): $CancellablePromise<$models.VirusScanRun> {
    return $Call.ByID(692703645, entityID, mode);
}

export function SavePlayState(state: $models.PlayState): $CancellablePromise<$models.PlayState> {
    return $Call.ByID(1809947574, state);
}

export function SaveSettings(update: $models.SettingsUpdate): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3784651466, update);
}

export function SaveSetup(input: $models.SetupInput): $CancellablePromise<$models.SetupResult> {
    return $Call.ByID(654217000, input);
}

export function SaveWorkspaceDraft(workspaceID: string, relativePath: string, content: string, baseSHA256: string): $CancellablePromise<void> {
    return $Call.ByID(4251899839, workspaceID, relativePath, content, baseSHA256);
}

export function ScanLibrary(): $CancellablePromise<$models.ScanSummary> {
    return $Call.ByID(1511987522);
}

export function SearchWorkspace(workspaceID: string, options: $models.WorkspaceSearchOptions, maxResults: number): $CancellablePromise<$models.WorkspaceSearchMatch[] | null> {
    return $Call.ByID(2068548899, workspaceID, options, maxResults);
}

export function SendVirgilMessage(sessionID: string, prompt: string, modelOverride: string): $CancellablePromise<$models.AgentRunRecord> {
    return $Call.ByID(311073238, sessionID, prompt, modelOverride);
}

export function SetCollectionChildren(collectionID: string, childIDs: string[] | null, included: boolean): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(256002693, collectionID, childIDs, included);
}

export function SetCollectionChildrenEnabled(collectionID: string, childIDs: string[] | null, enabled: boolean): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(2233447422, collectionID, childIDs, enabled);
}

/**
 * SetCollectionCover validates and persists a stable artwork recipe. Single
 * and collage recipes are rendered once into the same content-addressed cache
 * used by library thumbnails; cards therefore never reopen source archives.
 */
export function SetCollectionCover(collectionID: string, cover: $models.CollectionCover): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(823798825, collectionID, cover);
}

export function SetCollectionMods(collectionID: string, entityIDs: string[] | null, included: boolean): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(3883164791, collectionID, entityIDs, included);
}

export function SetCollectionModsEnabled(collectionID: string, entityIDs: string[] | null, enabled: boolean): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(1406279852, collectionID, entityIDs, enabled);
}

export function SetEntityPreviewFromArchive(entityID: string, memberPath: string): $CancellablePromise<$models.LibraryItem> {
    return $Call.ByID(2556088127, entityID, memberPath);
}

export function SetEntityPreviewFromFile(entityID: string, sourcePath: string): $CancellablePromise<$models.LibraryItem> {
    return $Call.ByID(602868577, entityID, sourcePath);
}

export function SetLibraryItemTags(entityID: string, tagIDs: string[] | null): $CancellablePromise<$models.LibraryItem> {
    return $Call.ByID(91975591, entityID, tagIDs);
}

export function SetWorkspaceJSONValue(workspaceID: string, relativePath: string, dottedPath: string, value: any): $CancellablePromise<void> {
    return $Call.ByID(195891334, workspaceID, relativePath, dottedPath, value);
}

export function Settings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3630548879);
}

export function StageWorkspaceGitPaths(workspaceID: string, paths: string[] | null, expectedFingerprint: string): $CancellablePromise<$models.GitStatus> {
    return $Call.ByID(1771313425, workspaceID, paths, expectedFingerprint);
}

export function StartAIConnection(providerID: string): $CancellablePromise<$models.AIConnectionStart> {
    return $Call.ByID(2091354552, providerID);
}

/**
 * StartGitHubPublish starts the confirmed create/connect, remote, push, and
 * verification operation asynchronously.
 */
export function StartGitHubPublish(request: $models.GitHubPublishStartRequest): $CancellablePromise<$models.GitHubPublishOperation> {
    return $Call.ByID(1298198628, request);
}

/**
 * StartGitHubPublishAuth starts a fresh GitHub OAuth App device flow.
 */
export function StartGitHubPublishAuth(): $CancellablePromise<$models.GitHubPublishAuthSession> {
    return $Call.ByID(1739550690);
}

export function StartVirgilSession(workspaceID: string, prompt: string, modelOverride: string, userTitle: string): $CancellablePromise<$models.VirgilSessionRecord> {
    return $Call.ByID(1890900807, workspaceID, prompt, modelOverride, userTitle);
}

export function StopAgent(runID: string): $CancellablePromise<boolean> {
    return $Call.ByID(1641704647, runID);
}

export function SubmitAIConnection(loginID: string, requestID: string, value: string): $CancellablePromise<void> {
    return $Call.ByID(987952920, loginID, requestID, value);
}

export function SwitchWorkspaceGitBranch(workspaceID: string, name: string, expectedFingerprint: string): $CancellablePromise<$models.GitStatus> {
    return $Call.ByID(1476270185, workspaceID, name, expectedFingerprint);
}

export function SyncWorkspaceGit(workspaceID: string, expectedFingerprint: string): $CancellablePromise<$models.GitOperationResult> {
    return $Call.ByID(908040546, workspaceID, expectedFingerprint);
}

export function UninstallTest(workspaceID: string): $CancellablePromise<void> {
    return $Call.ByID(3380044888, workspaceID);
}

export function UnstageWorkspaceGitPaths(workspaceID: string, paths: string[] | null, expectedFingerprint: string): $CancellablePromise<$models.GitStatus> {
    return $Call.ByID(2788470166, workspaceID, paths, expectedFingerprint);
}

export function UpdateCollection(collectionID: string, name: string, description: string): $CancellablePromise<$models.CollectionDetail> {
    return $Call.ByID(3840286075, collectionID, name, description);
}

export function UpdateLibraryItemDetails(entityID: string, update: $models.LibraryItemDetailsUpdate): $CancellablePromise<$models.EntityDetail> {
    return $Call.ByID(3924468085, entityID, update);
}

export function UpdateLibraryVariant(entityID: string, update: $models.LibraryVariantUpdate): $CancellablePromise<$models.EntityDetail> {
    return $Call.ByID(2339916167, entityID, update);
}

export function UpdateModTagVisual(tagID: string, color: string, icon: string): $CancellablePromise<$models.OrganizationState> {
    return $Call.ByID(719045307, tagID, color, icon);
}

export function UpdatePlayProfile(profileID: string, collectionIDs: string[] | null): $CancellablePromise<$models.ModProfile> {
    return $Call.ByID(3672296970, profileID, collectionIDs);
}

export function ValidateWorkspace(workspaceID: string): $CancellablePromise<modkit$0.ValidationResult> {
    return $Call.ByID(1665736785, workspaceID);
}

export function VirusScanMetadata(entityID: string): $CancellablePromise<$models.ModSecurityMetadata> {
    return $Call.ByID(983667179, entityID);
}

export function WorkspaceDiff(workspaceID: string): $CancellablePromise<modkit$0.WorkspaceChange[] | null> {
    return $Call.ByID(1837507304, workspaceID);
}

export function WriteWorkspaceFile(workspaceID: string, relativePath: string, content: string, expectedSHA256: string): $CancellablePromise<void> {
    return $Call.ByID(1515493856, workspaceID, relativePath, content, expectedSHA256);
}
