// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modkit$0 from "../beamworlds-modkit/models.js";

export interface AIConnectionEvent {
    "loginId": string;
    "providerId": string;
    "status": string;
    "message"?: string;
    "requestId"?: string;
    "inputLabel"?: string;
}

export interface AIConnectionStart {
    "loginId": string;
    "providerId": string;
    "url": string;
    "instructions": string;
}

export interface AIConnectionState {
    "providers": AIProviderConnection[] | null;
    "activeProfile": string;
}

export interface AIProviderConnection {
    "id": string;
    "label": string;
    "method": string;
    "connected": boolean;
}

export interface AIUsage {
    "hasRuns": boolean;
    "runCount": number;
    "totalTokens": number;
    "limits": UsageLimit[] | null;
    "usageError"?: string;
}

export interface AgentActivity {
    "runId": string;
    "sessionId": string;
    "workspaceId": string;
    "at": string;
    "type": string;
    "message"?: string;
    "delta"?: string;
    "toolName"?: string;
    "isError"?: boolean;
    "data"?: { [_ in string]?: any } | null;
}

export interface AgentEventRecord {
    "id": number;
    "runId": string;
    "at": string;
    "type": string;
    "message": string;
    "data": { [_ in string]?: any } | null;
}

export interface AgentModelOption {
    "provider": string;
    "id": string;
    "selector": string;
    "name": string;
    "contextWindow": number;
    "reasoning": boolean;
}

export interface AgentRunRecord {
    "id": string;
    "sessionId": string;
    "workspaceId": string;
    "prompt": string;
    "status": string;
    "startedAt": string;
    "finishedAt": string;
    "finalText": string;
    "error": string;
}

export interface AppConfig {
    "setupComplete"?: boolean;
    "beamngRoot": string;
    "activeModsDir": string;
    "libraryDir": string;
    "gameInstallDir": string;
    "scanRoots": string[] | null;
    "scanConcurrency": number;
    "dataDir"?: string;
    "configPath": string;
    "projectRoot": string;
    "databasePath": string;
    "imageCacheDir": string;
    "workspaceDir": string;
    "exportDir": string;
    "profileDir": string;
    "testInstallDir": string;
    "gameExecutable": string;
}

export interface AppSettings {
    "theme": string;
    "interfaceSize": string;
    "textSize": string;
    "defaultAuthor": string;
    "agentProfile": string;
    "agentModel": string;
    "contextMode": string;
    "showAIUsage": boolean;
    "showFileSizes": boolean;
    "autoFormatDelayMs": number;
    "emphasisColor": string;
    "activeTabColor": string;
    "subsectionTitleColor": string;
    "darkSurfaceColor": string;
    "darkBorderColor": string;
    "darkTextColor": string;
    "lightSurfaceColor": string;
    "lightBorderColor": string;
    "lightTextColor": string;
    "scrollbarColor": string;
    "preScanModel": string;
    "preScanReasoning": string;
    "fullScanModel": string;
    "fullScanReasoning": string;
    "hasOpenRouterApiKey": boolean;
    "hasOpenAIApiKey": boolean;
    "hasAnthropicApiKey": boolean;
}

export interface ArchiveFileRemovalImpact {
    "files": ArchiveFileTarget[] | null;
    "refusals": string[] | null;
    "archiveCount": number;
    "archiveBytes": number;
}

export interface ArchiveFileTarget {
    "linkId": string;
    "entityId": string;
    "displayName": string;
    "archivePath": string;
    "sizeBytes": number;
    "missing": boolean;
}

export interface ArchiveLink {
    "id": string;
    "artifactId": string;
    "path": string;
    "rootPath": string;
    "linked": boolean;
    "sizeBytes": number;
    "modifiedAt": string;
    "discoveredAt": string;
    "lastSeenAt": string;
}

export interface ArchiveMemberPreview {
    "path": string;
    "kind": string;
    "mime": string;
    "text": string;
    "dataUrl": string;
    "sizeBytes": number;
    "truncated": boolean;
}

/**
 * ArchiveResult reports state transitions completed by an archive operation.
 * Archiving and restoring are intentionally metadata-only: archive links,
 * files, memberships (as rows), tags, workspaces, and scan rows are left
 * untouched. Archiving does, however, disable enabled memberships and record
 * the flag so restoring can reverse exactly those disablements.
 */
export interface ArchiveResult {
    "archived": number;
    "restored": number;
    "disabledMemberships": number;
    "reenabledMemberships": number;
    "failures": string[] | null;
}

export interface CollectionArtworkCandidate {
    "path": string;
    "name": string;
    "url": string;
    "assetId": string;
}

/**
 * A parent -> child edge. Disabling it stops traversal through this edge only;
 * the child still contributes anywhere else it is reached.
 */
export interface CollectionChild {
    "collectionId": string;
    "enabled": boolean;
}

export interface CollectionCover {
    "mode": string;
    "images": CollectionCoverImage[] | null;
}

export interface CollectionCoverImage {
    "assetId": string;
    "focalX": number;
    "focalY": number;
}

export interface CollectionDetail {
    "collection": ModCollection;
    "members": CollectionMember[] | null;
    "children": CollectionChild[] | null;
    "mods": CollectionMod[] | null;
    "usage": CollectionUsage;
}

/**
 * A membership row: the mod stays in the collection when disabled, it just
 * stops contributing to a resolved selection. DisabledByArchive marks
 * memberships that were auto-disabled when the mod was archived; restoring
 * the mod re-enables only these, leaving user-disabled memberships untouched.
 */
export interface CollectionMember {
    "entityId": string;
    "enabled": boolean;
    "disabledByArchive": boolean;
}

export interface CollectionMod {
    "entityId": string;
    "displayName": string;
    "kind": modkit$0.Kind;
    "archivePath": string;
    "archivedAt": string;
    "sha256": string;
    "sizeBytes": number;
    "thumbnailUrl": string;
    "available": boolean;
    "collectionIds": string[] | null;
    "rootIds": string[] | null;
}

export interface CollectionReference {
    "id": string;
    "name": string;
}

export interface CollectionUsage {
    "collections": CollectionReference[] | null;
    "profiles": CollectionReference[] | null;
}

export interface Dashboard {
    "linked": number;
    "unlinked": number;
    "vehicles": number;
    "maps": number;
    "uiAndScripts": number;
    "workspaces": number;
    "entities": number;
    "artifacts": number;
    "cachedAssets": number;
    "cachedAssetBytes": number;
    "lastScanAt": string;
    "lastSuccessfulScanAt": string;
    "lastScanStatus": string;
    "lastScanFound": number;
    "lastScanAnalyzed": number;
    "lastScanFailed": number;
    "latestEvents": EventRecord[] | null;
    "databaseBytes": number;
}

export interface EntityDetail {
    "item": LibraryItem;
    "links": ArchiveLink[] | null;
    "history": EventRecord[] | null;
    "historyTotal": number;
}

export interface EntityPreviewCandidate {
    "memberPath": string;
    "label": string;
    "width": number;
    "height": number;
    "sizeBytes": number;
    "assetSha": string;
    "selected": boolean;
    "automatic": boolean;
}

export interface EventRecord {
    "id": number;
    "at": string;
    "entityId": string;
    "type": string;
    "data": { [_ in string]?: any } | null;
}

export interface ExportRecord {
    "id": string;
    "workspaceId": string;
    "artifactId": string;
    "path": string;
    "sha256": string;
    "kind": string;
    "createdAt": string;
}

export interface ExportResponse {
    "record": ExportRecord;
    "result": modkit$0.ExportResult;
}

export interface GitBranch {
    "name": string;
    "commit": string;
    "current": boolean;
}

/**
 * GitCommitResult reports the commit made from the staged index only.
 */
export interface GitCommitResult {
    "hash": string;
    "shortHash": string;
    "message": string;
    "branch": string;
    "detached": boolean;
    "amended": boolean;
    "status": GitStatus;
    "outputTruncated": boolean;
}

/**
 * GitDiff is a real Git diff for one path. Patch is empty when Git has no
 * textual patch to show; Binary, Unsupported, and Conflict explain why.
 */
export interface GitDiff {
    "path": string;
    "originalPath"?: string;
    "comparison": string;
    "available": boolean;
    "binary": boolean;
    "unsupported": boolean;
    "conflict": boolean;
    "status": string;
    "patch": string;
    "message": string;
    "outputTruncated": boolean;
}

/**
 * GitDiscardFailure identifies a selected path that could not be discarded.
 * Completed paths are reported separately so a partial command failure cannot
 * be mistaken for an atomic batch.
 */
export interface GitDiscardFailure {
    "path": string;
    "error": string;
}

export interface GitDiscardResult {
    "success": boolean;
    "stale": boolean;
    "completed": string[] | null;
    "failed": GitDiscardFailure[] | null;
    "error": string;
    "status": GitStatus;
    "outputTruncated": boolean;
}

/**
 * GitHubPublishAuthSession is the device-flow state exposed to the UI. Device
 * and access tokens are deliberately absent; only the user code intended for
 * display and the verified account are returned.
 */
export interface GitHubPublishAuthSession {
    "sessionId": string;
    "configured": boolean;
    "state": string;
    "login": string;
    "userCode": string;
    "verificationUri": string;
    "expiresAt": string;
    "expiresInSeconds": number;
    "pollIntervalSeconds": number;
    "nextPollAt": string;
    "grantedScopes": string[] | null;
    "errorCode": string;
    "error": string;
    "action": string;
    "retryable": boolean;
}

/**
 * GitHubPublishConfiguration describes only non-secret integration setup.
 */
export interface GitHubPublishConfiguration {
    "provider": string;
    "configured": boolean;
    "clientIdConfigured": boolean;
    "scope": string;
    "visibilityOptions": string[] | null;
    "message": string;
    "action": string;
}

/**
 * GitHubPublishDraft is a fresh repository draft. Visibility is normalized to
 * exactly "private" or "public" by the backend; an empty value means private.
 */
export interface GitHubPublishDraft {
    "sessionId": string;
    "workspaceId": string;
    "name": string;
    "description": string;
    "visibility": string;
    "publicConfirmed": boolean;
}

/**
 * GitHubPublishLocalState captures the exact local state used for the
 * preflight and reconciliation decision.
 */
export interface GitHubPublishLocalState {
    "root": string;
    "gitDirectory": string;
    "repository": boolean;
    "currentBranch": string;
    "detached": boolean;
    "mainAvailable": boolean;
    "mainOid": string;
    "remotes": GitHubPublishRemote[] | null;
}

/**
 * GitHubPublishOperation is the asynchronously polled operation/result.
 */
export interface GitHubPublishOperation {
    "operationId": string;
    "sessionId": string;
    "state": string;
    "steps": GitHubPublishStep[] | null;
    "partial": GitHubPublishPartialState;
    "error": string;
    "action": string;
    "retryable": boolean;
    "reconciliationRequired": boolean;
    "cancelled": boolean;
    "completed": boolean;
}

/**
 * GitHubPublishPartialState remains truthful after cancellation or a partial
 * transfer. It intentionally contains no credential or provider token.
 */
export interface GitHubPublishPartialState {
    "createdUrl": string;
    "repositoryUrl": string;
    "remoteName": string;
    "remoteUrl": string;
    "remoteState": string;
    "remoteAdded": boolean;
    "remoteReused": boolean;
    "pushState": string;
    "upstreamVerified": boolean;
    "upstreamRemote": string;
    "upstreamMerge": string;
}

/**
 * GitHubPublishPreflight is a read-only plan. Nothing in this call creates a
 * repository or changes the local Git configuration.
 */
export interface GitHubPublishPreflight {
    "planId": string;
    "sessionId": string;
    "ready": boolean;
    "visibility": string;
    "visibilityOptions": string[] | null;
    "owner": string;
    "name": string;
    "description": string;
    "targetUrl": string;
    "local": GitHubPublishLocalState;
    "target": GitHubPublishTarget;
    "proposedRemoteName": string;
    "proposedRemoteUrl": string;
    "existingOrigin"?: GitHubPublishRemote | null;
    "requiresFinalConfirmation": boolean;
    "requiresPublicConfirmation": boolean;
    "requiresConnectConfirmation": boolean;
    "creationUnknown": boolean;
    "reconciliationRequired": boolean;
    "retryable": boolean;
    "error": string;
    "action": string;
}

/**
 * GitHubPublishRemote is a secret-free view of one local remote.
 */
export interface GitHubPublishRemote {
    "name": string;
    "fetchUrl": string;
    "pushUrl": string;
    "matchesTarget": boolean;
}

/**
 * GitHubPublishStartRequest is the final, explicit confirmation boundary.
 */
export interface GitHubPublishStartRequest {
    "planId": string;
    "sessionId": string;
    "confirmed": boolean;
    "publicConfirmed": boolean;
    "connectExisting": boolean;
    "retryUnknownCreation": boolean;
}

/**
 * GitHubPublishStep is one ordered state-machine step.
 */
export interface GitHubPublishStep {
    "name": string;
    "state": string;
    "attempt": number;
    "message": string;
}

/**
 * GitHubPublishTarget distinguishes an accessible collision from GitHub's
 * deliberately ambiguous not-found response.
 */
export interface GitHubPublishTarget {
    "owner": string;
    "name": string;
    "url": string;
    "cloneUrl": string;
    "repositoryId": number;
    "state": string;
    "exists": boolean;
    "accessKnown": boolean;
    "accessible": boolean;
    "canPush": boolean;
    "private": boolean;
    "description": string;
    "error": string;
    "action": string;
}

/**
 * GitInitializationResult is the recoverable outcome of automatic repository
 * setup for a new mod. A failed result never implies that the scaffold was
 * removed; the path remains available for manual recovery.
 */
export interface GitInitializationResult {
    "status": string;
    "stage": string;
    "path": string;
    "message": string;
    "nextAction": string;
}

/**
 * GitOperationResult reports a remote operation and its refreshed status.
 */
export interface GitOperationResult {
    "operation": string;
    "success": boolean;
    "output": string;
    "stderr": string;
    "error": string;
    "steps": GitOperationStep[] | null;
    "status": GitStatus;
    "outputTruncated": boolean;
}

/**
 * GitOperationStep records one conventional Git command in a remote or sync
 * operation. Sync always records fetch, then pull, then push until a step
 * fails.
 */
export interface GitOperationStep {
    "operation": string;
    "success": boolean;
    "output": string;
    "stderr": string;
    "error": string;
    "outputTruncated": boolean;
}

/**
 * GitRemote describes one remote configured in the workspace repository.
 */
export interface GitRemote {
    "name": string;
    "fetchURL": string;
    "pushURL": string;
}

/**
 * GitStatus is a snapshot of the exact repository rooted at a workspace's
 * FilesRoot. Fingerprint is stable for an unchanged poll and changes when Git
 * state or the relevant working-tree metadata changes.
 */
export interface GitStatus {
    "repository": boolean;
    "state": string;
    "clean": boolean;
    "root": string;
    "branch": string;
    "detached": boolean;
    "upstream": string;
    "ahead": number;
    "behind": number;
    "remotes": GitRemote[] | null;
    "conflicts": GitStatusEntry[] | null;
    "staged": GitStatusEntry[] | null;
    "unstaged": GitStatusEntry[] | null;
    "untracked": GitStatusEntry[] | null;
    "fingerprint": string;
    "outputTruncated": boolean;
}

/**
 * GitStatusEntry is one path in a Git status group. IndexCode and
 * WorktreeCode retain Git's two-column porcelain state so a path can be in
 * both Staged and Unstaged at the same time.
 */
export interface GitStatusEntry {
    "path": string;
    "originalPath"?: string;
    "status": string;
    "indexCode": string;
    "worktreeCode": string;
    "statusCode": string;
    "staged": boolean;
    "unstaged": boolean;
    "untracked": boolean;
    "conflict": boolean;
    "renamed": boolean;
    "copied": boolean;
    "binary": boolean;
    "deleted": boolean;
    "unsupported": boolean;
}

export interface KnowledgeDocument {
    "id": string;
    "title": string;
    "content": string;
}

/**
 * LibraryGroupPage is the paged result returned by LibraryGroupPage.
 */
export interface LibraryGroupPage {
    "rows": LibraryGroupRow[] | null;
    "totalRows": number;
    "distinctMods": number;
    "page": number;
    "pageSize": number;
}

/**
 * LibraryGroupRow is one row in the paged group stream.
 */
export interface LibraryGroupRow {
    /**
     * "group" | "mod"
     */
    "rowType": string;

    /**
     * tag ID, or ungroupedGroupID
     */
    "groupId": string;

    /**
     * group name; empty for mod rows
     */
    "label": string;

    /**
     * group rows only
     */
    "modCount": number;

    /**
     * group rows only
     */
    "sizeBytes": number;

    /**
     * group rows only
     */
    "collapsed": boolean;

    /**
     * group rows only, while a search is active
     */
    "matchCount": number;

    /**
     * mod rows only
     */
    "item": LibraryItem | null;
}

export interface LibraryItem {
    "entityId": string;
    "revision": string;
    "archivedAt": string;
    "artifactId": string;
    "linkId": string;
    "collectionIds": string[] | null;
    "displayName": string;
    "kind": modkit$0.Kind;
    "sourceId": string;
    "source": string;
    "archivePath": string;
    "rootPath": string;
    "linked": boolean;
    "sizeBytes": number;
    "modifiedAt": string;
    "lastSeenAt": string;
    "fingerprint": string;
    "sha256": string;
    "thumbnailUrl": string;
    "memberCount": number;
    "namespaceCount": number;
    "variantCount": number;
    "issueCount": number;
    "healthStatus": string;
    "healthLabel": string;
    "lastSecurityScanAt": string;
    "lastSecurityScanVerdict": string;
    "lastSecurityScanSha256": string;
    "securityScanChanged": boolean;
    "manifest": modkit$0.Manifest;
    "tags": ModTag[] | null;
}

export interface LibraryItemDetailsUpdate {
    "description": string;
    "author": string;
    "version": string;
}

export interface LibraryVariantUpdate {
    "configPath": string;
    "configuration": string;
    "description": string;
    "configType": string;
    "bodyStyle": string;
    "drivetrain": string;
    "transmission": string;
    "fuelType": string;
    "propulsion": string;
    "power": string;
    "torque": string;
    "weight": string;
    "value": string;
    "topSpeed": string;
}

export interface ModCollection {
    "id": string;
    "name": string;
    "description": string;
    "updatedAt": string;
    "position": number;
    "modCount": number;
    "archivedModCount": number;
    "directModCount": number;
    "directEnabledCount": number;
    "childCount": number;
    "childIds": string[] | null;
    "parentIds": string[] | null;
    "cover": CollectionCover;
    "coverUrl": string;
}

export interface ModFamily {
    "id": string;
    "confidence": string;
    "kind": string;
    "title": string;
    "author": string;
    "resourceId": string;
    "members": ModFamilyMember[] | null;
    "reclaimableBytes": number;
}

export interface ModFamilyMember {
    "entityId": string;
    "linkId": string;
    "displayName": string;
    "title": string;
    "author": string;
    "version": string;
    "archivePath": string;
    "sizeBytes": number;
    "modifiedAt": string;
    "sha256": string;
    "sourceLabel": string;
    "collections": string[] | null;
    "workspaceCount": number;
    "thumbnailUrl": string;
    "entryCount": number;
    "variantCount": number;
    "namespaces": string[] | null;
    "issueCount": number;
    "issueSeverity": string;
    "healthStatus": string;
    "installedInGame": boolean;
    "keeper": boolean;
    "keeperReason": string;
}

export interface ModImportDirectory {
    "path": string;
    "parentPath": string;
    "breadcrumbs": ModImportLocation[] | null;
    "locations": ModImportLocation[] | null;
    "recentLocations": ModImportLocation[] | null;
    "entries": ModImportEntry[] | null;
    "destinationPath": string;
    "warning": string;
}

export interface ModImportEntry {
    "name": string;
    "path": string;
    "isDirectory": boolean;
    "sizeBytes": number;
    "modifiedAt": string;
}

export interface ModImportFailure {
    "path": string;
    "message": string;
}

export interface ModImportLocation {
    "name": string;
    "path": string;
    "kind": string;
}

export interface ModImportResult {
    "items": LibraryItem[] | null;
    "failures": ModImportFailure[] | null;
    "importedCount": number;
    "existingCount": number;
}

export interface ModProfile {
    "id": string;
    "name": string;
    "updatedAt": string;
    "collectionIds": string[] | null;
    "collectionCount": number;
    "modCount": number;
}

/**
 * ModRemovalImpact is what the confirmation needs to state plainly before the
 * user agrees to anything.
 */
export interface ModRemovalImpact {
    "mods": ModRemovalTarget[] | null;
    "collections": string[] | null;
    "workspaces": string[] | null;
    "archiveCount": number;
    "archiveBytes": number;
}

export interface ModRemovalResult {
    "forgotten": number;
    "recycled": number;
    "failures": string[] | null;
}

export interface ModRemovalTarget {
    "entityId": string;
    "displayName": string;
    "archivePath": string;
    "sizeBytes": number;
    "missing": boolean;
}

export interface ModSecurityMetadata {
    "schemaVersion": number;
    "entityId": string;
    "updatedAt": string;
    "securityScans": VirusScanStageReference[] | null;
}

export interface ModTag {
    "id": string;
    "name": string;
    "color": string;
    "icon": string;
    "origin": string;
    "grouped": boolean;
    "modCount": number;
}

export interface NewModRequest {
    "name": string;
    "modId": string;
    "kind": string;
    "author": string;
    "version": string;
    "description": string;
}

export interface OrganizationState {
    "collections": ModCollection[] | null;
    "tags": ModTag[] | null;
    "profiles": ModProfile[] | null;
}

export interface PlayActivation {
    "operationId": string;
    "modCount": number;
    "userPath": string;
    "modsPath": string;
    "activatedAt": string;
    "collectionIds": string[] | null;
    "fingerprint": string;
}

export interface PlayProgress {
    "operationId": string;
    "phase": string;
    "current": string;
    "error": string;
    "completed": number;
    "total": number;
    "bytesCopied": number;
    "totalBytes": number;
    "done": boolean;
}

export interface PlayRequest {
    "collectionIds": string[] | null;
    "fingerprint": string;
}

export interface PlayResult {
    "applied": boolean;
    "started": boolean;
    "activation": PlayActivation;
    "process": ProcessLaunch;
    "error": string;
    "processUncertain": boolean;
}

export interface PlayRuntimeState {
    "applied": boolean;
    "activation": PlayActivation;
    "gameRunning": boolean;
    "warning": string;
}

export interface PlaySelection {
    "collectionIds": string[] | null;
    "includedCollectionIds": string[] | null;
    "mods": CollectionMod[] | null;
    "modCount": number;
    "missingCount": number;
    "archivedCount": number;
    "fingerprint": string;
    "warnings": string[] | null;
}

export interface PlayState {
    "profileId": string;
    "collectionIds": string[] | null;
    "defaultCollectionIds": string[] | null;
    "notices": string[] | null;
}

export interface ProcessLaunch {
    "pid": number;
    "executable": string;
    "startedAt": string;
}

export interface RuntimeDiagnostic {
    "severity": string;
    "component": string;
    "message": string;
    "line": number;
    "relevant": boolean;
}

export interface RuntimeReport {
    "logPath": string;
    "fromOffset": number;
    "toOffset": number;
    "freshBytes": number;
    "truncated": boolean;
    "errors": number;
    "warnings": number;
    "relevantHits": number;
    "diagnostics": RuntimeDiagnostic[] | null;
    "analyzedAt": string;
}

export interface ScanProgress {
    "scanId": string;
    "phase": string;
    "path": string;
    "discovered": number;
    "analyzed": number;
    "cached": number;
    "failed": number;
    "done": boolean;
    "error"?: string;
}

export interface ScanSummary {
    "scanId": string;
    "startedAt": string;
    "finishedAt": string;
    "discovered": number;
    "analyzed": number;
    "cached": number;
    "failed": number;
    "cancelled": boolean;
    "error"?: string;
}

export interface SettingsUpdate {
    "theme": string;
    "interfaceSize": string;
    "textSize": string;
    "defaultAuthor": string;
    "agentProfile": string;
    "agentModel": string;
    "contextMode": string;
    "showAIUsage": boolean;
    "showFileSizes": boolean;
    "autoFormatDelayMs": number;
    "emphasisColor": string;
    "activeTabColor": string;
    "subsectionTitleColor": string;
    "darkSurfaceColor": string;
    "darkBorderColor": string;
    "darkTextColor": string;
    "lightSurfaceColor": string;
    "lightBorderColor": string;
    "lightTextColor": string;
    "scrollbarColor": string;
    "preScanModel": string;
    "preScanReasoning": string;
    "fullScanModel": string;
    "fullScanReasoning": string;
    "openRouterApiKey": string;
    "clearOpenRouterApiKey": boolean;
    "openAIApiKey": string;
    "clearOpenAIAPIKey": boolean;
    "anthropicApiKey": string;
    "clearAnthropicAPIKey": boolean;
}

export interface SetupInput {
    "beamngRoot": string;
    "activeModsDir": string;
    "libraryDir": string;
    "gameInstallDir": string;
    "dataDir": string;
    "additionalScanRoots": string[] | null;
}

export interface SetupResult {
    "config": AppConfig;
    "restartRequired": boolean;
}

export interface SetupState {
    "required": boolean;
    "suggested": SetupInput;
    "configPath": string;
    "nativeModCount": number;
    "nativeEnabledCount": number;
}

export interface TestInstallRecord {
    "id": string;
    "workspaceId": string;
    "exportId": string;
    "path": string;
    "sha256": string;
    "installedAt": string;
    "logBaselineAt": string;
    "logPath": string;
    "logOffset": number;
    "active": boolean;
}

export interface UsageLimit {
    "provider": string;
    "label": string;
    "windowId": string;
    "used": number;
    "remaining": number;
    "limit": number;
    "unit": string;
    "resetsAt": number;
    "status": string;
}

export interface VirgilSessionRecord {
    "id": string;
    "workspaceId": string;
    "profile": string;
    "runtimeSessionId": string;
    "title": string;
    "runtimeTitle": string;
    "userTitle": string;
    "status": string;
    "lastError": string;
    "tabOrder": number;
    "createdAt": string;
    "updatedAt": string;
    "runs": AgentRunRecord[] | null;
    "summary"?: VirgilSessionSummary | null;
}

/**
 * VirgilSessionSummary is calculated from persisted run events and workspace
 * mutations. It is intentionally not stored in the durable session row: the
 * values are a read model for the editor status bar.
 */
export interface VirgilSessionSummary {
    "sessionId": string;
    "workspaceId": string;
    "status": string;
    "startedAt": string;
    "finishedAt": string;
    "changeMode"?: string;
    "addedLines"?: number | null;
    "removedLines"?: number | null;
    "inputTokens"?: number | null;
    "outputTokens"?: number | null;
    "totalTokens"?: number | null;
    "contextUsed"?: number | null;
    "contextLimit"?: number | null;
}

export interface VirusScanProgress {
    "scanId": string;
    "entityId": string;
    "mode": string;
    "status": string;
    "stage": string;
    "stageIndex": number;
    "stageTotal": number;
    "message": string;
    "error": string;
}

export interface VirusScanRun {
    "id": string;
    "entityId": string;
    "artifactId": string;
    "fileSha256": string;
    "mode": string;
    "status": string;
    "currentStage": string;
    "verdict": string;
    "createdAt": string;
    "updatedAt": string;
    "error": string;
    "stages": VirusScanStage[] | null;
}

export interface VirusScanStage {
    "id": string;
    "scanId": string;
    "entityId": string;
    "artifactId": string;
    "fileSha256": string;
    "stage": string;
    "status": string;
    "createdAt": string;
    "completedAt": string;
    "parameters": { [_ in string]?: string } | null;
    "inputs": string[] | null;
    "metadataFile": string;
    "auditId": string;
    "summary": string;
    "error": string;
}

export interface VirusScanStageReference {
    "id": string;
    "scanId": string;
    "artifactId": string;
    "stage": string;
    "createdAt": string;
    "metadataFile": string;
    "inputs": string[] | null;
}

export interface WorkspaceDetail {
    "workspace": WorkspaceRecord;
    "entity": LibraryItem;
    "files": modkit$0.FileSnapshot[] | null;
    "directories": string[] | null;
    "drafts": WorkspaceDraft[] | null;
    "validation": modkit$0.ValidationResult;
    "exports": ExportRecord[] | null;
    "virgilSessions": VirgilSessionRecord[] | null;
    "knowledge": KnowledgeDocument[] | null;
    "activeTest"?: TestInstallRecord | null;
    "diskBytes": number;
    "gitInitialization": GitInitializationResult;
}

export interface WorkspaceDraft {
    "path": string;
    "content": string;
    "baseSha256": string;
    "updatedAt": string;
}

export interface WorkspaceRecord {
    "id": string;
    "entityId": string;
    "artifactId": string;
    "root": string;
    "filesRoot": string;
    "sourcePath": string;
    "sourceSha256": string;
    "createdAt": string;
    "updatedAt": string;
    "status": string;
    "lastValidation": string;
    "displayName": string;
    "kind": modkit$0.Kind;
    "virgilConfigured": boolean;
    "virgilEnabled": boolean;
    "agentRunId": string;
    "agentGoal": string;
    "agentStatus": string;
    "agentProcess": string;
    "agentUpdatedAt": string;
}

export interface WorkspaceSearchMatch {
    "relativePath": string;
    "line": number;
    "column": number;
    "matchLength": number;
    "preview": string;
}

export interface WorkspaceSearchOptions {
    "query": string;
    "regex": boolean;
    "caseSensitive": boolean;
}

export interface WorkspaceTextFile {
    "path": string;
    "content": string;
    "sha256": string;
}
