// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modkit$0 from "../beamworlds-modkit/models.js";

export interface AIUsage {
    "hasRuns": boolean;
    "runCount": number;
    "totalTokens": number;
    "limits": UsageLimit[] | null;
    "usageError"?: string;
}

export interface AgentActivity {
    "runId": string;
    "at": string;
    "type": string;
    "message"?: string;
    "delta"?: string;
    "toolName"?: string;
    "isError"?: boolean;
    "data"?: { [_ in string]?: any } | null;
}

export interface AgentEventRecord {
    "id": number;
    "runId": string;
    "at": string;
    "type": string;
    "message": string;
    "data": { [_ in string]?: any } | null;
}

export interface AgentModelOption {
    "provider": string;
    "id": string;
    "selector": string;
    "name": string;
    "contextWindow": number;
    "reasoning": boolean;
}

export interface AgentRunRecord {
    "id": string;
    "workspaceId": string;
    "prompt": string;
    "status": string;
    "startedAt": string;
    "finishedAt": string;
    "finalText": string;
    "error": string;
}

export interface AppConfig {
    "setupComplete"?: boolean;
    "beamngRoot": string;
    "activeModsDir": string;
    "libraryDir": string;
    "gameInstallDir": string;
    "scanRoots": string[] | null;
    "scanConcurrency": number;
    "dataDir"?: string;
    "ompPath"?: string;
    "configPath": string;
    "projectRoot": string;
    "databasePath": string;
    "imageCacheDir": string;
    "workspaceDir": string;
    "exportDir": string;
    "profileDir": string;
    "testInstallDir": string;
    "gameExecutable": string;
}

export interface AppSettings {
    "theme": string;
    "defaultAuthor": string;
    "agentProfile": string;
    "agentModel": string;
    "contextMode": string;
    "showAIUsage": boolean;
    "showFileSizes": boolean;
    "emphasisColor": string;
    "activeTabColor": string;
    "darkSurfaceColor": string;
    "darkBorderColor": string;
    "darkTextColor": string;
    "lightSurfaceColor": string;
    "lightBorderColor": string;
    "lightTextColor": string;
    "preScanModel": string;
    "preScanReasoning": string;
    "fullScanModel": string;
    "fullScanReasoning": string;
    "hasApiKey": boolean;
}

export interface ArchiveLink {
    "id": string;
    "artifactId": string;
    "path": string;
    "rootPath": string;
    "linked": boolean;
    "sizeBytes": number;
    "modifiedAt": string;
    "discoveredAt": string;
    "lastSeenAt": string;
}

export interface Dashboard {
    "linked": number;
    "unlinked": number;
    "vehicles": number;
    "maps": number;
    "uiAndScripts": number;
    "workspaces": number;
    "entities": number;
    "artifacts": number;
    "cachedAssets": number;
    "cachedAssetBytes": number;
    "lastScanAt": string;
    "lastScanStatus": string;
    "lastScanFound": number;
    "lastScanAnalyzed": number;
    "lastScanFailed": number;
    "latestEvents": EventRecord[] | null;
    "databaseBytes": number;
}

export interface EntityDetail {
    "item": LibraryItem;
    "links": ArchiveLink[] | null;
    "history": EventRecord[] | null;
}

export interface EventRecord {
    "id": number;
    "at": string;
    "entityId": string;
    "type": string;
    "data": { [_ in string]?: any } | null;
}

export interface ExportRecord {
    "id": string;
    "workspaceId": string;
    "artifactId": string;
    "path": string;
    "sha256": string;
    "kind": string;
    "createdAt": string;
}

export interface ExportResponse {
    "record": ExportRecord;
    "result": modkit$0.ExportResult;
}

export interface KnowledgeDocument {
    "id": string;
    "title": string;
    "content": string;
}

export interface LibraryFolder {
    "id": string;
    "name": string;
    "parentId": string;
    "modCount": number;
}

export interface LibraryItem {
    "entityId": string;
    "artifactId": string;
    "linkId": string;
    "folderId": string;
    "displayName": string;
    "kind": modkit$0.Kind;
    "archivePath": string;
    "rootPath": string;
    "linked": boolean;
    "sizeBytes": number;
    "modifiedAt": string;
    "lastSeenAt": string;
    "fingerprint": string;
    "sha256": string;
    "thumbnailUrl": string;
    "memberCount": number;
    "namespaceCount": number;
    "variantCount": number;
    "issueCount": number;
    "healthStatus": string;
    "healthLabel": string;
    "lastSecurityScanAt": string;
    "manifest": modkit$0.Manifest;
    "tags": ModTag[] | null;
}

export interface ModPreset {
    "id": string;
    "name": string;
    "description": string;
    "modCount": number;
    "defaultForProfileCount": number;
}

export interface ModProfile {
    "id": string;
    "name": string;
    "defaultPresetId": string;
    "presetCount": number;
    "modCount": number;
}

export interface ModSecurityMetadata {
    "schemaVersion": number;
    "entityId": string;
    "updatedAt": string;
    "securityScans": VirusScanStageReference[] | null;
}

export interface ModTag {
    "id": string;
    "name": string;
    "modCount": number;
}

export interface NewModRequest {
    "name": string;
    "modId": string;
    "kind": string;
    "author": string;
    "version": string;
    "description": string;
}

export interface OrganizationState {
    "folders": LibraryFolder[] | null;
    "tags": ModTag[] | null;
    "presets": ModPreset[] | null;
    "profiles": ModProfile[] | null;
}

export interface PresetDetail {
    "preset": ModPreset;
    "entityIds": string[] | null;
}

export interface ProcessLaunch {
    "pid": number;
    "executable": string;
    "startedAt": string;
}

export interface ProfileActivation {
    "profileId": string;
    "profileName": string;
    "userPath": string;
    "modsPath": string;
    "modCount": number;
    "activatedAt": string;
}

export interface ProfileDetail {
    "profile": ModProfile;
    "presets": ProfilePreset[] | null;
    "mods": ProfileMod[] | null;
}

export interface ProfileLaunch {
    "activation": ProfileActivation;
    "process": ProcessLaunch;
}

export interface ProfileMod {
    "entityId": string;
    "displayName": string;
    "kind": modkit$0.Kind;
    "archivePath": string;
    "sha256": string;
    "sizeBytes": number;
    "presetIds": string[] | null;
}

export interface ProfilePreset {
    "id": string;
    "name": string;
    "description": string;
    "modCount": number;
    "selected": boolean;
    "default": boolean;
}

export interface ProfileProgress {
    "profileId": string;
    "phase": string;
    "current": string;
    "completed": number;
    "total": number;
    "bytesCopied": number;
    "totalBytes": number;
    "done": boolean;
    "error"?: string;
}

export interface RuntimeDiagnostic {
    "severity": string;
    "component": string;
    "message": string;
    "line": number;
    "relevant": boolean;
}

export interface RuntimeReport {
    "logPath": string;
    "fromOffset": number;
    "toOffset": number;
    "freshBytes": number;
    "truncated": boolean;
    "errors": number;
    "warnings": number;
    "relevantHits": number;
    "diagnostics": RuntimeDiagnostic[] | null;
    "analyzedAt": string;
}

export interface ScanProgress {
    "scanId": string;
    "phase": string;
    "path": string;
    "discovered": number;
    "analyzed": number;
    "cached": number;
    "failed": number;
    "done": boolean;
    "error"?: string;
}

export interface ScanSummary {
    "scanId": string;
    "startedAt": string;
    "finishedAt": string;
    "discovered": number;
    "analyzed": number;
    "cached": number;
    "failed": number;
    "cancelled": boolean;
    "error"?: string;
}

export interface SettingsUpdate {
    "theme": string;
    "defaultAuthor": string;
    "agentProfile": string;
    "agentModel": string;
    "contextMode": string;
    "showAIUsage": boolean;
    "showFileSizes": boolean;
    "emphasisColor": string;
    "activeTabColor": string;
    "darkSurfaceColor": string;
    "darkBorderColor": string;
    "darkTextColor": string;
    "lightSurfaceColor": string;
    "lightBorderColor": string;
    "lightTextColor": string;
    "preScanModel": string;
    "preScanReasoning": string;
    "fullScanModel": string;
    "fullScanReasoning": string;
    "apiKey": string;
    "clearApiKey": boolean;
}

export interface SetupInput {
    "beamngRoot": string;
    "activeModsDir": string;
    "libraryDir": string;
    "gameInstallDir": string;
    "dataDir": string;
    "additionalScanRoots": string[] | null;
}

export interface SetupResult {
    "config": AppConfig;
    "restartRequired": boolean;
}

export interface SetupState {
    "required": boolean;
    "suggested": SetupInput;
    "configPath": string;
    "nativeModCount": number;
    "nativeEnabledCount": number;
}

export interface TestInstallRecord {
    "id": string;
    "workspaceId": string;
    "exportId": string;
    "path": string;
    "sha256": string;
    "installedAt": string;
    "logBaselineAt": string;
    "logPath": string;
    "logOffset": number;
    "active": boolean;
}

export interface UsageLimit {
    "provider": string;
    "label": string;
    "windowId": string;
    "used": number;
    "remaining": number;
    "limit": number;
    "unit": string;
    "resetsAt": number;
    "status": string;
}

export interface VirusScanProgress {
    "scanId": string;
    "entityId": string;
    "mode": string;
    "status": string;
    "stage": string;
    "stageIndex": number;
    "stageTotal": number;
    "message": string;
    "error": string;
}

export interface VirusScanRun {
    "id": string;
    "entityId": string;
    "artifactId": string;
    "mode": string;
    "status": string;
    "currentStage": string;
    "verdict": string;
    "createdAt": string;
    "updatedAt": string;
    "error": string;
    "stages": VirusScanStage[] | null;
}

export interface VirusScanStage {
    "id": string;
    "scanId": string;
    "entityId": string;
    "artifactId": string;
    "stage": string;
    "status": string;
    "createdAt": string;
    "completedAt": string;
    "parameters": { [_ in string]?: string } | null;
    "inputs": string[] | null;
    "metadataFile": string;
    "auditId": string;
    "summary": string;
    "error": string;
}

export interface VirusScanStageReference {
    "id": string;
    "scanId": string;
    "artifactId": string;
    "stage": string;
    "createdAt": string;
    "metadataFile": string;
    "inputs": string[] | null;
}

export interface WorkspaceDetail {
    "workspace": WorkspaceRecord;
    "entity": LibraryItem;
    "files": modkit$0.FileSnapshot[] | null;
    "directories": string[] | null;
    "drafts": WorkspaceDraft[] | null;
    "validation": modkit$0.ValidationResult;
    "exports": ExportRecord[] | null;
    "agentRuns": AgentRunRecord[] | null;
    "knowledge": KnowledgeDocument[] | null;
    "activeTest"?: TestInstallRecord | null;
    "diskBytes": number;
}

export interface WorkspaceDraft {
    "path": string;
    "content": string;
    "updatedAt": string;
}

export interface WorkspaceRecord {
    "id": string;
    "entityId": string;
    "artifactId": string;
    "root": string;
    "filesRoot": string;
    "sourcePath": string;
    "sourceSha256": string;
    "createdAt": string;
    "updatedAt": string;
    "status": string;
    "lastValidation": string;
    "displayName": string;
    "kind": modkit$0.Kind;
    "agentStatus": string;
    "agentUpdatedAt": string;
}

export interface WorkspaceTextFile {
    "path": string;
    "content": string;
}
