// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modkit$0 from "../beamworlds-modkit/models.js";

export class AIUsage {
    /**
     * Creates a new AIUsage instance.
     * @param {Partial<AIUsage>} [$$source = {}] - The source object to create the AIUsage.
     */
    constructor($$source = {}) {
        if (!("hasRuns" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasRuns"] = false;
        }
        if (!("runCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["runCount"] = 0;
        }
        if (!("totalTokens" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalTokens"] = 0;
        }
        if (!("limits" in $$source)) {
            /**
             * @member
             * @type {UsageLimit[]}
             */
            this["limits"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["usageError"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AIUsage instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AIUsage}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("limits" in $$parsedSource) {
            $$parsedSource["limits"] = $$createField3_0($$parsedSource["limits"]);
        }
        return new AIUsage(/** @type {Partial<AIUsage>} */($$parsedSource));
    }
}

export class AgentActivity {
    /**
     * Creates a new AgentActivity instance.
     * @param {Partial<AgentActivity>} [$$source = {}] - The source object to create the AgentActivity.
     */
    constructor($$source = {}) {
        if (!("runId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["at"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["delta"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["toolName"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {boolean | undefined}
             */
            this["isError"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["data"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentActivity instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentActivity}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField7_0($$parsedSource["data"]);
        }
        return new AgentActivity(/** @type {Partial<AgentActivity>} */($$parsedSource));
    }
}

export class AgentEventRecord {
    /**
     * Creates a new AgentEventRecord instance.
     * @param {Partial<AgentEventRecord>} [$$source = {}] - The source object to create the AgentEventRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("runId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["runId"] = "";
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["at"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["data"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentEventRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentEventRecord}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField5_0($$parsedSource["data"]);
        }
        return new AgentEventRecord(/** @type {Partial<AgentEventRecord>} */($$parsedSource));
    }
}

export class AgentModelOption {
    /**
     * Creates a new AgentModelOption instance.
     * @param {Partial<AgentModelOption>} [$$source = {}] - The source object to create the AgentModelOption.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("selector" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["selector"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("contextWindow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["contextWindow"] = 0;
        }
        if (!("reasoning" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["reasoning"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentModelOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentModelOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentModelOption(/** @type {Partial<AgentModelOption>} */($$parsedSource));
    }
}

export class AgentRunRecord {
    /**
     * Creates a new AgentRunRecord instance.
     * @param {Partial<AgentRunRecord>} [$$source = {}] - The source object to create the AgentRunRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("workspaceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspaceId"] = "";
        }
        if (!("prompt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["prompt"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "";
        }
        if (!("finishedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["finishedAt"] = "";
        }
        if (!("finalText" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["finalText"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["error"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AgentRunRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AgentRunRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AgentRunRecord(/** @type {Partial<AgentRunRecord>} */($$parsedSource));
    }
}

export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("beamngRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["beamngRoot"] = "";
        }
        if (!("activeModsDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activeModsDir"] = "";
        }
        if (!("libraryDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["libraryDir"] = "";
        }
        if (!("gameInstallDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gameInstallDir"] = "";
        }
        if (!("scanRoots" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["scanRoots"] = [];
        }
        if (!("scanConcurrency" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["scanConcurrency"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["dataDir"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["ompPath"] = undefined;
        }
        if (!("configPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["configPath"] = "";
        }
        if (!("projectRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["projectRoot"] = "";
        }
        if (!("databasePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["databasePath"] = "";
        }
        if (!("imageCacheDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["imageCacheDir"] = "";
        }
        if (!("workspaceDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspaceDir"] = "";
        }
        if (!("exportDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["exportDir"] = "";
        }
        if (!("profileDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profileDir"] = "";
        }
        if (!("testInstallDir" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["testInstallDir"] = "";
        }
        if (!("gameExecutable" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["gameExecutable"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("scanRoots" in $$parsedSource) {
            $$parsedSource["scanRoots"] = $$createField4_0($$parsedSource["scanRoots"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("defaultAuthor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultAuthor"] = "";
        }
        if (!("agentProfile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentProfile"] = "";
        }
        if (!("agentModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentModel"] = "";
        }
        if (!("contextMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contextMode"] = "";
        }
        if (!("showAIUsage" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showAIUsage"] = false;
        }
        if (!("hasApiKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["hasApiKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

export class ArchiveLink {
    /**
     * Creates a new ArchiveLink instance.
     * @param {Partial<ArchiveLink>} [$$source = {}] - The source object to create the ArchiveLink.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("artifactId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactId"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("rootPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rootPath"] = "";
        }
        if (!("linked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["linked"] = false;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("modifiedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modifiedAt"] = "";
        }
        if (!("discoveredAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["discoveredAt"] = "";
        }
        if (!("lastSeenAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSeenAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ArchiveLink instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ArchiveLink}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ArchiveLink(/** @type {Partial<ArchiveLink>} */($$parsedSource));
    }
}

export class Dashboard {
    /**
     * Creates a new Dashboard instance.
     * @param {Partial<Dashboard>} [$$source = {}] - The source object to create the Dashboard.
     */
    constructor($$source = {}) {
        if (!("linked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["linked"] = 0;
        }
        if (!("unlinked" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["unlinked"] = 0;
        }
        if (!("vehicles" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["vehicles"] = 0;
        }
        if (!("maps" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["maps"] = 0;
        }
        if (!("uiAndScripts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["uiAndScripts"] = 0;
        }
        if (!("workspaces" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["workspaces"] = 0;
        }
        if (!("entities" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entities"] = 0;
        }
        if (!("artifacts" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["artifacts"] = 0;
        }
        if (!("cachedAssets" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cachedAssets"] = 0;
        }
        if (!("cachedAssetBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cachedAssetBytes"] = 0;
        }
        if (!("lastScanAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastScanAt"] = "";
        }
        if (!("lastScanStatus" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastScanStatus"] = "";
        }
        if (!("lastScanFound" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastScanFound"] = 0;
        }
        if (!("lastScanAnalyzed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastScanAnalyzed"] = 0;
        }
        if (!("lastScanFailed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["lastScanFailed"] = 0;
        }
        if (!("latestEvents" in $$source)) {
            /**
             * @member
             * @type {EventRecord[]}
             */
            this["latestEvents"] = [];
        }
        if (!("databaseBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["databaseBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Dashboard instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Dashboard}
     */
    static createFrom($$source = {}) {
        const $$createField15_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("latestEvents" in $$parsedSource) {
            $$parsedSource["latestEvents"] = $$createField15_0($$parsedSource["latestEvents"]);
        }
        return new Dashboard(/** @type {Partial<Dashboard>} */($$parsedSource));
    }
}

export class EntityDetail {
    /**
     * Creates a new EntityDetail instance.
     * @param {Partial<EntityDetail>} [$$source = {}] - The source object to create the EntityDetail.
     */
    constructor($$source = {}) {
        if (!("item" in $$source)) {
            /**
             * @member
             * @type {LibraryItem}
             */
            this["item"] = (new LibraryItem());
        }
        if (!("links" in $$source)) {
            /**
             * @member
             * @type {ArchiveLink[]}
             */
            this["links"] = [];
        }
        if (!("history" in $$source)) {
            /**
             * @member
             * @type {EventRecord[]}
             */
            this["history"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntityDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EntityDetail}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType6;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("item" in $$parsedSource) {
            $$parsedSource["item"] = $$createField0_0($$parsedSource["item"]);
        }
        if ("links" in $$parsedSource) {
            $$parsedSource["links"] = $$createField1_0($$parsedSource["links"]);
        }
        if ("history" in $$parsedSource) {
            $$parsedSource["history"] = $$createField2_0($$parsedSource["history"]);
        }
        return new EntityDetail(/** @type {Partial<EntityDetail>} */($$parsedSource));
    }
}

export class EventRecord {
    /**
     * Creates a new EventRecord instance.
     * @param {Partial<EventRecord>} [$$source = {}] - The source object to create the EventRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["at"] = "";
        }
        if (!("entityId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityId"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("data" in $$source)) {
            /**
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["data"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EventRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {EventRecord}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("data" in $$parsedSource) {
            $$parsedSource["data"] = $$createField4_0($$parsedSource["data"]);
        }
        return new EventRecord(/** @type {Partial<EventRecord>} */($$parsedSource));
    }
}

export class ExportRecord {
    /**
     * Creates a new ExportRecord instance.
     * @param {Partial<ExportRecord>} [$$source = {}] - The source object to create the ExportRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("workspaceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspaceId"] = "";
        }
        if (!("artifactId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactId"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExportRecord(/** @type {Partial<ExportRecord>} */($$parsedSource));
    }
}

export class ExportResponse {
    /**
     * Creates a new ExportResponse instance.
     * @param {Partial<ExportResponse>} [$$source = {}] - The source object to create the ExportResponse.
     */
    constructor($$source = {}) {
        if (!("record" in $$source)) {
            /**
             * @member
             * @type {ExportRecord}
             */
            this["record"] = (new ExportRecord());
        }
        if (!("result" in $$source)) {
            /**
             * @member
             * @type {modkit$0.ExportResult}
             */
            this["result"] = (new modkit$0.ExportResult());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExportResponse instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExportResponse}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType9;
        const $$createField1_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("record" in $$parsedSource) {
            $$parsedSource["record"] = $$createField0_0($$parsedSource["record"]);
        }
        if ("result" in $$parsedSource) {
            $$parsedSource["result"] = $$createField1_0($$parsedSource["result"]);
        }
        return new ExportResponse(/** @type {Partial<ExportResponse>} */($$parsedSource));
    }
}

export class KnowledgeDocument {
    /**
     * Creates a new KnowledgeDocument instance.
     * @param {Partial<KnowledgeDocument>} [$$source = {}] - The source object to create the KnowledgeDocument.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnowledgeDocument instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnowledgeDocument}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KnowledgeDocument(/** @type {Partial<KnowledgeDocument>} */($$parsedSource));
    }
}

export class LibraryFolder {
    /**
     * Creates a new LibraryFolder instance.
     * @param {Partial<LibraryFolder>} [$$source = {}] - The source object to create the LibraryFolder.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("modCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryFolder instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LibraryFolder}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new LibraryFolder(/** @type {Partial<LibraryFolder>} */($$parsedSource));
    }
}

export class LibraryItem {
    /**
     * Creates a new LibraryItem instance.
     * @param {Partial<LibraryItem>} [$$source = {}] - The source object to create the LibraryItem.
     */
    constructor($$source = {}) {
        if (!("entityId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityId"] = "";
        }
        if (!("artifactId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactId"] = "";
        }
        if (!("linkId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["linkId"] = "";
        }
        if (!("folderId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {modkit$0.Kind}
             */
            this["kind"] = modkit$0.Kind.$zero;
        }
        if (!("archivePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivePath"] = "";
        }
        if (!("rootPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rootPath"] = "";
        }
        if (!("linked" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["linked"] = false;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("modifiedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modifiedAt"] = "";
        }
        if (!("lastSeenAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastSeenAt"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("thumbnailUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thumbnailUrl"] = "";
        }
        if (!("memberCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["memberCount"] = 0;
        }
        if (!("namespaceCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["namespaceCount"] = 0;
        }
        if (!("variantCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["variantCount"] = 0;
        }
        if (!("issueCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["issueCount"] = 0;
        }
        if (!("manifest" in $$source)) {
            /**
             * @member
             * @type {modkit$0.Manifest}
             */
            this["manifest"] = (new modkit$0.Manifest());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new LibraryItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {LibraryItem}
     */
    static createFrom($$source = {}) {
        const $$createField19_0 = $$createType11;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("manifest" in $$parsedSource) {
            $$parsedSource["manifest"] = $$createField19_0($$parsedSource["manifest"]);
        }
        return new LibraryItem(/** @type {Partial<LibraryItem>} */($$parsedSource));
    }
}

export class ModPreset {
    /**
     * Creates a new ModPreset instance.
     * @param {Partial<ModPreset>} [$$source = {}] - The source object to create the ModPreset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("modCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modCount"] = 0;
        }
        if (!("defaultForProfileCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["defaultForProfileCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModPreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModPreset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModPreset(/** @type {Partial<ModPreset>} */($$parsedSource));
    }
}

export class ModProfile {
    /**
     * Creates a new ModProfile instance.
     * @param {Partial<ModProfile>} [$$source = {}] - The source object to create the ModProfile.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("defaultPresetId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultPresetId"] = "";
        }
        if (!("presetCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["presetCount"] = 0;
        }
        if (!("modCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModProfile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModProfile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModProfile(/** @type {Partial<ModProfile>} */($$parsedSource));
    }
}

export class NewModRequest {
    /**
     * Creates a new NewModRequest instance.
     * @param {Partial<NewModRequest>} [$$source = {}] - The source object to create the NewModRequest.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("modId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modId"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["kind"] = "";
        }
        if (!("author" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["author"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NewModRequest instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NewModRequest}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new NewModRequest(/** @type {Partial<NewModRequest>} */($$parsedSource));
    }
}

export class OrganizationState {
    /**
     * Creates a new OrganizationState instance.
     * @param {Partial<OrganizationState>} [$$source = {}] - The source object to create the OrganizationState.
     */
    constructor($$source = {}) {
        if (!("folders" in $$source)) {
            /**
             * @member
             * @type {LibraryFolder[]}
             */
            this["folders"] = [];
        }
        if (!("presets" in $$source)) {
            /**
             * @member
             * @type {ModPreset[]}
             */
            this["presets"] = [];
        }
        if (!("profiles" in $$source)) {
            /**
             * @member
             * @type {ModProfile[]}
             */
            this["profiles"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OrganizationState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {OrganizationState}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType13;
        const $$createField1_0 = $$createType15;
        const $$createField2_0 = $$createType17;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folders" in $$parsedSource) {
            $$parsedSource["folders"] = $$createField0_0($$parsedSource["folders"]);
        }
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField1_0($$parsedSource["presets"]);
        }
        if ("profiles" in $$parsedSource) {
            $$parsedSource["profiles"] = $$createField2_0($$parsedSource["profiles"]);
        }
        return new OrganizationState(/** @type {Partial<OrganizationState>} */($$parsedSource));
    }
}

export class PresetDetail {
    /**
     * Creates a new PresetDetail instance.
     * @param {Partial<PresetDetail>} [$$source = {}] - The source object to create the PresetDetail.
     */
    constructor($$source = {}) {
        if (!("preset" in $$source)) {
            /**
             * @member
             * @type {ModPreset}
             */
            this["preset"] = (new ModPreset());
        }
        if (!("entityIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["entityIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PresetDetail}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType14;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("preset" in $$parsedSource) {
            $$parsedSource["preset"] = $$createField0_0($$parsedSource["preset"]);
        }
        if ("entityIds" in $$parsedSource) {
            $$parsedSource["entityIds"] = $$createField1_0($$parsedSource["entityIds"]);
        }
        return new PresetDetail(/** @type {Partial<PresetDetail>} */($$parsedSource));
    }
}

export class ProcessLaunch {
    /**
     * Creates a new ProcessLaunch instance.
     * @param {Partial<ProcessLaunch>} [$$source = {}] - The source object to create the ProcessLaunch.
     */
    constructor($$source = {}) {
        if (!("pid" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["pid"] = 0;
        }
        if (!("executable" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["executable"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessLaunch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessLaunch}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessLaunch(/** @type {Partial<ProcessLaunch>} */($$parsedSource));
    }
}

export class ProfileActivation {
    /**
     * Creates a new ProfileActivation instance.
     * @param {Partial<ProfileActivation>} [$$source = {}] - The source object to create the ProfileActivation.
     */
    constructor($$source = {}) {
        if (!("profileId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profileId"] = "";
        }
        if (!("profileName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["profileName"] = "";
        }
        if (!("userPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["userPath"] = "";
        }
        if (!("modsPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modsPath"] = "";
        }
        if (!("modCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modCount"] = 0;
        }
        if (!("activatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["activatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileActivation instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileActivation}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileActivation(/** @type {Partial<ProfileActivation>} */($$parsedSource));
    }
}

export class ProfileDetail {
    /**
     * Creates a new ProfileDetail instance.
     * @param {Partial<ProfileDetail>} [$$source = {}] - The source object to create the ProfileDetail.
     */
    constructor($$source = {}) {
        if (!("profile" in $$source)) {
            /**
             * @member
             * @type {ModProfile}
             */
            this["profile"] = (new ModProfile());
        }
        if (!("presets" in $$source)) {
            /**
             * @member
             * @type {ProfilePreset[]}
             */
            this["presets"] = [];
        }
        if (!("mods" in $$source)) {
            /**
             * @member
             * @type {ProfileMod[]}
             */
            this["mods"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileDetail}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType16;
        const $$createField1_0 = $$createType19;
        const $$createField2_0 = $$createType21;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("profile" in $$parsedSource) {
            $$parsedSource["profile"] = $$createField0_0($$parsedSource["profile"]);
        }
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField1_0($$parsedSource["presets"]);
        }
        if ("mods" in $$parsedSource) {
            $$parsedSource["mods"] = $$createField2_0($$parsedSource["mods"]);
        }
        return new ProfileDetail(/** @type {Partial<ProfileDetail>} */($$parsedSource));
    }
}

export class ProfileLaunch {
    /**
     * Creates a new ProfileLaunch instance.
     * @param {Partial<ProfileLaunch>} [$$source = {}] - The source object to create the ProfileLaunch.
     */
    constructor($$source = {}) {
        if (!("activation" in $$source)) {
            /**
             * @member
             * @type {ProfileActivation}
             */
            this["activation"] = (new ProfileActivation());
        }
        if (!("process" in $$source)) {
            /**
             * @member
             * @type {ProcessLaunch}
             */
            this["process"] = (new ProcessLaunch());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileLaunch instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileLaunch}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType22;
        const $$createField1_0 = $$createType23;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("activation" in $$parsedSource) {
            $$parsedSource["activation"] = $$createField0_0($$parsedSource["activation"]);
        }
        if ("process" in $$parsedSource) {
            $$parsedSource["process"] = $$createField1_0($$parsedSource["process"]);
        }
        return new ProfileLaunch(/** @type {Partial<ProfileLaunch>} */($$parsedSource));
    }
}

export class ProfileMod {
    /**
     * Creates a new ProfileMod instance.
     * @param {Partial<ProfileMod>} [$$source = {}] - The source object to create the ProfileMod.
     */
    constructor($$source = {}) {
        if (!("entityId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityId"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {modkit$0.Kind}
             */
            this["kind"] = modkit$0.Kind.$zero;
        }
        if (!("archivePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["archivePath"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("presetIds" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["presetIds"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileMod instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileMod}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presetIds" in $$parsedSource) {
            $$parsedSource["presetIds"] = $$createField6_0($$parsedSource["presetIds"]);
        }
        return new ProfileMod(/** @type {Partial<ProfileMod>} */($$parsedSource));
    }
}

export class ProfilePreset {
    /**
     * Creates a new ProfilePreset instance.
     * @param {Partial<ProfilePreset>} [$$source = {}] - The source object to create the ProfilePreset.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("modCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["modCount"] = 0;
        }
        if (!("selected" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["selected"] = false;
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["default"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfilePreset instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfilePreset}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfilePreset(/** @type {Partial<ProfilePreset>} */($$parsedSource));
    }
}

export class RuntimeDiagnostic {
    /**
     * Creates a new RuntimeDiagnostic instance.
     * @param {Partial<RuntimeDiagnostic>} [$$source = {}] - The source object to create the RuntimeDiagnostic.
     */
    constructor($$source = {}) {
        if (!("severity" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["severity"] = "";
        }
        if (!("component" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["component"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["message"] = "";
        }
        if (!("line" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["line"] = 0;
        }
        if (!("relevant" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["relevant"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeDiagnostic instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeDiagnostic}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeDiagnostic(/** @type {Partial<RuntimeDiagnostic>} */($$parsedSource));
    }
}

export class RuntimeReport {
    /**
     * Creates a new RuntimeReport instance.
     * @param {Partial<RuntimeReport>} [$$source = {}] - The source object to create the RuntimeReport.
     */
    constructor($$source = {}) {
        if (!("logPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logPath"] = "";
        }
        if (!("fromOffset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["fromOffset"] = 0;
        }
        if (!("toOffset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["toOffset"] = 0;
        }
        if (!("freshBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["freshBytes"] = 0;
        }
        if (!("truncated" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["truncated"] = false;
        }
        if (!("errors" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["errors"] = 0;
        }
        if (!("warnings" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["warnings"] = 0;
        }
        if (!("relevantHits" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["relevantHits"] = 0;
        }
        if (!("diagnostics" in $$source)) {
            /**
             * @member
             * @type {RuntimeDiagnostic[]}
             */
            this["diagnostics"] = [];
        }
        if (!("analyzedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["analyzedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeReport instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RuntimeReport}
     */
    static createFrom($$source = {}) {
        const $$createField8_0 = $$createType25;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("diagnostics" in $$parsedSource) {
            $$parsedSource["diagnostics"] = $$createField8_0($$parsedSource["diagnostics"]);
        }
        return new RuntimeReport(/** @type {Partial<RuntimeReport>} */($$parsedSource));
    }
}

export class ScanProgress {
    /**
     * Creates a new ScanProgress instance.
     * @param {Partial<ScanProgress>} [$$source = {}] - The source object to create the ScanProgress.
     */
    constructor($$source = {}) {
        if (!("scanId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scanId"] = "";
        }
        if (!("phase" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["phase"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("discovered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discovered"] = 0;
        }
        if (!("analyzed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["analyzed"] = 0;
        }
        if (!("cached" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cached"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("done" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["done"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanProgress(/** @type {Partial<ScanProgress>} */($$parsedSource));
    }
}

export class ScanSummary {
    /**
     * Creates a new ScanSummary instance.
     * @param {Partial<ScanSummary>} [$$source = {}] - The source object to create the ScanSummary.
     */
    constructor($$source = {}) {
        if (!("scanId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["scanId"] = "";
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["startedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("finishedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["finishedAt"] = "0001-01-01T00:00:00.000Z";
        }
        if (!("discovered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["discovered"] = 0;
        }
        if (!("analyzed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["analyzed"] = 0;
        }
        if (!("cached" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cached"] = 0;
        }
        if (!("failed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["failed"] = 0;
        }
        if (!("cancelled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["cancelled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ScanSummary instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ScanSummary}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ScanSummary(/** @type {Partial<ScanSummary>} */($$parsedSource));
    }
}

export class SettingsUpdate {
    /**
     * Creates a new SettingsUpdate instance.
     * @param {Partial<SettingsUpdate>} [$$source = {}] - The source object to create the SettingsUpdate.
     */
    constructor($$source = {}) {
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("defaultAuthor" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["defaultAuthor"] = "";
        }
        if (!("agentProfile" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentProfile"] = "";
        }
        if (!("agentModel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["agentModel"] = "";
        }
        if (!("contextMode" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["contextMode"] = "";
        }
        if (!("showAIUsage" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["showAIUsage"] = false;
        }
        if (!("apiKey" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["apiKey"] = "";
        }
        if (!("clearApiKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["clearApiKey"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsUpdate instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SettingsUpdate}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SettingsUpdate(/** @type {Partial<SettingsUpdate>} */($$parsedSource));
    }
}

export class TestInstallRecord {
    /**
     * Creates a new TestInstallRecord instance.
     * @param {Partial<TestInstallRecord>} [$$source = {}] - The source object to create the TestInstallRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("workspaceId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["workspaceId"] = "";
        }
        if (!("exportId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["exportId"] = "";
        }
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("sha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sha256"] = "";
        }
        if (!("installedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["installedAt"] = "";
        }
        if (!("logBaselineAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logBaselineAt"] = "";
        }
        if (!("logPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["logPath"] = "";
        }
        if (!("logOffset" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["logOffset"] = 0;
        }
        if (!("active" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["active"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestInstallRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestInstallRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestInstallRecord(/** @type {Partial<TestInstallRecord>} */($$parsedSource));
    }
}

export class UsageLimit {
    /**
     * Creates a new UsageLimit instance.
     * @param {Partial<UsageLimit>} [$$source = {}] - The source object to create the UsageLimit.
     */
    constructor($$source = {}) {
        if (!("provider" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["provider"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("windowId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["windowId"] = "";
        }
        if (!("used" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["used"] = 0;
        }
        if (!("remaining" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["remaining"] = 0;
        }
        if (!("limit" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["limit"] = 0;
        }
        if (!("unit" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["unit"] = "";
        }
        if (!("resetsAt" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["resetsAt"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UsageLimit instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UsageLimit}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UsageLimit(/** @type {Partial<UsageLimit>} */($$parsedSource));
    }
}

export class WorkspaceDetail {
    /**
     * Creates a new WorkspaceDetail instance.
     * @param {Partial<WorkspaceDetail>} [$$source = {}] - The source object to create the WorkspaceDetail.
     */
    constructor($$source = {}) {
        if (!("workspace" in $$source)) {
            /**
             * @member
             * @type {WorkspaceRecord}
             */
            this["workspace"] = (new WorkspaceRecord());
        }
        if (!("entity" in $$source)) {
            /**
             * @member
             * @type {LibraryItem}
             */
            this["entity"] = (new LibraryItem());
        }
        if (!("files" in $$source)) {
            /**
             * @member
             * @type {modkit$0.FileSnapshot[]}
             */
            this["files"] = [];
        }
        if (!("directories" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["directories"] = [];
        }
        if (!("drafts" in $$source)) {
            /**
             * @member
             * @type {WorkspaceDraft[]}
             */
            this["drafts"] = [];
        }
        if (!("validation" in $$source)) {
            /**
             * @member
             * @type {modkit$0.ValidationResult}
             */
            this["validation"] = (new modkit$0.ValidationResult());
        }
        if (!("exports" in $$source)) {
            /**
             * @member
             * @type {ExportRecord[]}
             */
            this["exports"] = [];
        }
        if (!("agentRuns" in $$source)) {
            /**
             * @member
             * @type {AgentRunRecord[]}
             */
            this["agentRuns"] = [];
        }
        if (!("knowledge" in $$source)) {
            /**
             * @member
             * @type {KnowledgeDocument[]}
             */
            this["knowledge"] = [];
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TestInstallRecord | null | undefined}
             */
            this["activeTest"] = undefined;
        }
        if (!("diskBytes" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["diskBytes"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDetail instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceDetail}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType26;
        const $$createField1_0 = $$createType6;
        const $$createField2_0 = $$createType28;
        const $$createField3_0 = $$createType3;
        const $$createField4_0 = $$createType30;
        const $$createField5_0 = $$createType31;
        const $$createField6_0 = $$createType32;
        const $$createField7_0 = $$createType34;
        const $$createField8_0 = $$createType36;
        const $$createField9_0 = $$createType38;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("workspace" in $$parsedSource) {
            $$parsedSource["workspace"] = $$createField0_0($$parsedSource["workspace"]);
        }
        if ("entity" in $$parsedSource) {
            $$parsedSource["entity"] = $$createField1_0($$parsedSource["entity"]);
        }
        if ("files" in $$parsedSource) {
            $$parsedSource["files"] = $$createField2_0($$parsedSource["files"]);
        }
        if ("directories" in $$parsedSource) {
            $$parsedSource["directories"] = $$createField3_0($$parsedSource["directories"]);
        }
        if ("drafts" in $$parsedSource) {
            $$parsedSource["drafts"] = $$createField4_0($$parsedSource["drafts"]);
        }
        if ("validation" in $$parsedSource) {
            $$parsedSource["validation"] = $$createField5_0($$parsedSource["validation"]);
        }
        if ("exports" in $$parsedSource) {
            $$parsedSource["exports"] = $$createField6_0($$parsedSource["exports"]);
        }
        if ("agentRuns" in $$parsedSource) {
            $$parsedSource["agentRuns"] = $$createField7_0($$parsedSource["agentRuns"]);
        }
        if ("knowledge" in $$parsedSource) {
            $$parsedSource["knowledge"] = $$createField8_0($$parsedSource["knowledge"]);
        }
        if ("activeTest" in $$parsedSource) {
            $$parsedSource["activeTest"] = $$createField9_0($$parsedSource["activeTest"]);
        }
        return new WorkspaceDetail(/** @type {Partial<WorkspaceDetail>} */($$parsedSource));
    }
}

export class WorkspaceDraft {
    /**
     * Creates a new WorkspaceDraft instance.
     * @param {Partial<WorkspaceDraft>} [$$source = {}] - The source object to create the WorkspaceDraft.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceDraft instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceDraft}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceDraft(/** @type {Partial<WorkspaceDraft>} */($$parsedSource));
    }
}

export class WorkspaceRecord {
    /**
     * Creates a new WorkspaceRecord instance.
     * @param {Partial<WorkspaceRecord>} [$$source = {}] - The source object to create the WorkspaceRecord.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("entityId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["entityId"] = "";
        }
        if (!("artifactId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["artifactId"] = "";
        }
        if (!("root" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["root"] = "";
        }
        if (!("filesRoot" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["filesRoot"] = "";
        }
        if (!("sourcePath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourcePath"] = "";
        }
        if (!("sourceSha256" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sourceSha256"] = "";
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["createdAt"] = "";
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["updatedAt"] = "";
        }
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("lastValidation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastValidation"] = "";
        }
        if (!("displayName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["displayName"] = "";
        }
        if (!("kind" in $$source)) {
            /**
             * @member
             * @type {modkit$0.Kind}
             */
            this["kind"] = modkit$0.Kind.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceRecord instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceRecord}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceRecord(/** @type {Partial<WorkspaceRecord>} */($$parsedSource));
    }
}

export class WorkspaceTextFile {
    /**
     * Creates a new WorkspaceTextFile instance.
     * @param {Partial<WorkspaceTextFile>} [$$source = {}] - The source object to create the WorkspaceTextFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("content" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["content"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WorkspaceTextFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WorkspaceTextFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WorkspaceTextFile(/** @type {Partial<WorkspaceTextFile>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = UsageLimit.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = EventRecord.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = LibraryItem.createFrom;
const $$createType7 = ArchiveLink.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = ExportRecord.createFrom;
const $$createType10 = modkit$0.ExportResult.createFrom;
const $$createType11 = modkit$0.Manifest.createFrom;
const $$createType12 = LibraryFolder.createFrom;
const $$createType13 = $Create.Array($$createType12);
const $$createType14 = ModPreset.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ModProfile.createFrom;
const $$createType17 = $Create.Array($$createType16);
const $$createType18 = ProfilePreset.createFrom;
const $$createType19 = $Create.Array($$createType18);
const $$createType20 = ProfileMod.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = ProfileActivation.createFrom;
const $$createType23 = ProcessLaunch.createFrom;
const $$createType24 = RuntimeDiagnostic.createFrom;
const $$createType25 = $Create.Array($$createType24);
const $$createType26 = WorkspaceRecord.createFrom;
const $$createType27 = modkit$0.FileSnapshot.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = WorkspaceDraft.createFrom;
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = modkit$0.ValidationResult.createFrom;
const $$createType32 = $Create.Array($$createType9);
const $$createType33 = AgentRunRecord.createFrom;
const $$createType34 = $Create.Array($$createType33);
const $$createType35 = KnowledgeDocument.createFrom;
const $$createType36 = $Create.Array($$createType35);
const $$createType37 = TestInstallRecord.createFrom;
const $$createType38 = $Create.Nullable($$createType37);
